### ISSUE TITLE
Bindsnet as Conda package

### ISSUE THREAD

**Issue by alex153490** [BindsNET/bindsnet#210]
It would be nice to have Bindsnet as Conda package in some channel. Currently I have PyTorch installation with Cond, but pip installation of Bindsnet is giving: 
  ```
Could not find a version that satisfies the requirement torch>=1.0.0 (from bindsnet) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch>=1.0.0 (from bindsnet)
```

So - pip is not seeing packages installed by Conda.

I tried:
`conda install --channel "pypi" bindsnet`
but it said, that the package can not be found

**Comment by Hananel-Hazan** [comment]
Thank you for using BindsNET.
pip and Conda are very different and the are isolated from each other. Therefore its seems that you need to install the requirements for BindsNET using pip

For more details using pip with Conda [link](https://www.anaconda.com/using-pip-in-a-conda-environment/)

In any case, at this moment we are not supporting Conda packages. 
However, we will glad if you can make one, feel free to submit a PR

**Comment by djsaunde** [comment]
Hi @alex153490, see [this SO post](https://stackoverflow.com/questions/41060382/using-pip-to-install-packages-to-anaconda-environment) for instructions on how to install packages with `pip` to a `conda` environment.

**Comment by Hananel-Hazan** [comment]
BindsNET is on conda, try it:
` conda install -c bindsnet bindsnet `
