### ISSUE TITLE
Storing the trained network parameters

### ISSUE THREAD

**Issue by rachmadvwp** [BindsNET/bindsnet#248]
Hi,
 
I was trying to simulate the training and testing subsequently using [this](https://github.com/djsaunde/bindsnet_experiments/blob/master/experiments/mnist/diehl_and_cook_2015.py) from BindsNET experiments repo.
However, I couldn't find the file that stores the trained network parameters. Could you please help me to identify which file used for storing the parameters? It should be in *.pt right? This to ensure that my testing phase is using the correct stored parameters.

Many thanks.

**Comment by djsaunde** [comment]
You can store it using any file name. I use *.pt to follow PyTorch convention but it doesn't matter either way.

**Comment by rachmadvwp** [comment]
My problem is I couldn't find *.pt that the training is supposed to generate.
If I use the default setting, as follows
> data_path = os.path.join(ROOT_DIR, 'data', 'MNIST')
> params_path = os.path.join(ROOT_DIR, 'params', data, model)
> curves_path = os.path.join(ROOT_DIR, 'curves', data, model)
> results_path = os.path.join(ROOT_DIR, 'results', data, model)
> confusion_path = os.path.join(ROOT_DIR, 'confusion', data, model)
I should get the file generated under /experiments/params folder right?

**Comment by djsaunde** [comment]
Yes, that's right. Is `bindsnet.network.Network.save` being called anywhere? Can you confirm it gets called? Might also help to print out the path where the parameters are being saved to double check.

**Comment by rachmadvwp** [comment]
I don't think so. Because I just used the default [file](https://github.com/djsaunde/bindsnet_experiments/blob/master/experiments/mnist/diehl_and_cook_2015.py). I was thinking it should be handled by line [172](https://github.com/djsaunde/bindsnet_experiments/blob/master/experiments/mnist/diehl_and_cook_2015.py#L172).
`network.save(os.path.join(params_path, model_name + '.pt'))`.

**Comment by Hananel-Hazan** [comment]
Right, that will save the network object with all the parameters that include in the network object.

**Comment by rachmadvwp** [comment]
it is strange since I couldn't find the generated file. 
Could you please confirm, if I just use the default example without changing anything,, will the parameters file be stored under /experiments/params folder? Or it is supposed to be somewhere else? If so, where should it be? Thanks a lot for the help

**Comment by Hananel-Hazan** [comment]
Currently, this code is not compatible with the new version of BindsNET. It need to be adapted to the current changes.
I confirm that if you install commit `3dd609f500f377e57aae29e932e62ebd26801ac0` and comment the line number 20 and add this line under 20 
`ROOT_DIR = 'test'`

When you run the code, it will save the files under your current path under new directory listed in `ROOT_DIR `

```
adam@eve:~/git repos/bindsnet_experiments/experiments/mnist/test$ ls
confusion  curves  data  params  results  spikes

```

**Comment by rachmadvwp** [comment]
Unfortunately i couldn't find this commit on "https://github.com/djsaunde/bindsnet_experiments/commit/3dd609f500f377e57aae29e932e62ebd26801ac0". Is the number correct?

**Comment by rachmadvwp** [comment]
It is running now. Let's see the final results later.
Another thing that remains, if the training is done,, we just need to change the mode to the testing phase without any changes on the setting or we still need to set the `network.learning = False` in [here](https://github.com/Hananel-Hazan/bindsnet/blob/4021360cc0f715947bf6dc3f7effab003141cb4c/bindsnet/network/__init__.py#L27)?

Many thanks

**Comment by djsaunde** [comment]
Changing the mode to test in the script will 1) load the network from disk, and 2) disable the learning rule and freeze the adaptive thresholds. Setting network.learning = False will only disable the learning rule. So, it's up to you, and what you want to do for the test phase.

**Comment by djsaunde** [comment]
An easy way to debug these kinds of scripts is to run shorter train / test phases, to get the result quicker. Try running with 500 train, 500 test, so you can quickly tell whether the save / load functions are working.

**Comment by rachmadvwp** [comment]
OK thanks a lot for the help.
I'll close the issue for now and might re-open it if needed.

**Comment by rachmadvwp** [comment]
Hi,
I'd like to ask. I have run [this](https://github.com/BINDS-LAB-UMASS/bindsnet_experiments/blob/master/experiments/mnist/diehl_and_cook_2015.py) example with no problem as per previous suggestion. However, when I try to use the same setting in a new PC, this [line](https://github.com/BINDS-LAB-UMASS/bindsnet_experiments/blob/8a20be9d1ede021b70ff95cc7e85024ff5a222db/experiments/mnist/diehl_and_cook_2015.py#L22) hinders the code from running, with the following error message.

> Traceback (most recent call last):
>   File "diehl_and_cook_2015.py", line 22, in <module>
>     from experiments.utils import update_curves, print_results
> ModuleNotFoundError: No module named 'experiments'

I tried some actions that I found online but it is still not working. What should be the solution?
Thanks in advance.

**Comment by Hananel-Hazan** [comment]
Try to use the 'eth_mnist.py' in the example directory and lets us know if the issue exists.
