### ISSUE TITLE
Reorganize Examples

### ISSUE THREAD

**Issue by dee0512** [BindsNET/bindsnet#312]
Examples to be removed:

- [x] space_invaders/et_space_invaders.py
- [x] space_invaders/minimal_space_invaders.py
- [x] space_invaders/random_baseline.py
- [x] asteroids/random_network_baseline.py
- [x] datasets/davis.py
- [x] datasets/spoken_mnist.py
- [x] mnist/batch_conv_mnist.py
- [x] mnist/minimal_mnist.py
- [x] mnist/minimal_resevoir.py
- [x] mnist/minimal_supervised_mnist.py
- [x] cifar10/*
- [x] notebooks/LIFNodes\ vs.\ CurrentLIFNodes.ipynb

Examples to be added:

- [x] breakout/random_baseline.py
- [x] breakout/random_network_baseline.py

Examples to be moved:
- [x] datasets/conv.py -> tensorboard/tensorboard.py
- [ ] benchmark -> separate repo

**Comment by dee0512** [comment]
@djsaunde can we move notebooks to bindsnet examples? We are planning to keep only examples that are required to help you understand Bindsnet. This would also reduce our workload when updating BindsNET.

**Comment by djsaunde** [comment]
Yes, I think that's for the best. We've been talking for a while about removing a bunch of examples, since they're out of date / not super informative.

**Comment by sharath** [comment]
I think we should move BindsNET to an organization repo and move the benchmark stuff to a separate repo under this organization.

**Comment by djsaunde** [comment]
Yup, I'm in the process of convincing Robert to let us move BindsNET to a BINDS GitHub organization

**Comment by Hananel-Hazan** [comment]
This is not relevant to this thread nor to public forum.
There is a plan to move to an organization, that plan involve lots of moving parts. Currently, BindsNET is in the right place to take advantage of that plan.

**Comment by dee0512** [comment]
So what do we do with the benchmarking examples? They require brian, ANNarchy, etc. which are not part of Bindsnet and are not relevant to normal users.

**Comment by dee0512** [comment]
Also, can everyone react to this comment to confirm all the examples to be removed? We tried to remove redundant and non-useful examples. Objections are welcome. 

@Hananel-Hazan 
@djsaunde 
@sharath 
@coopersigrist

**Comment by Hananel-Hazan** [comment]
I think:
1. benchmark can be in docs and not in examples.  This script is needed to reproduce the figure in the BindsNET paper
2. All the examples in the BindsNET paper need to stay.
3. Minimal and not minimal need to be combine to one example (if any)

Open to suggestions

**Comment by dee0512** [comment]
I agree with Hananel on most of the points. But:

The examples in the Bindsnet paper might not be relevant anymore. For eg. Pipeline. 

People can learn how to use datasets from the Docs. Same goes for neurons, architectures and learning rules. One Atari example should be enough to show how to work with rewards in RL. 
So, I would suggest that instead of writing and maintaining an example for every major update, we update the documentation.

**Comment by Hananel-Hazan** [comment]
Yes, you right, pipeline and datasets can be in the documents. But, although the examples from the paper are less relevant today, they are the first that going to be use by people that been introduce to the framework by reading the paper (quite a lots of people if you look on frontier page counter). 

Still some example need to be maintain, not all people read the doc first, some clone and run the examples first before diving to the documents to see what else the framework can do. 
Therefore we need to choose top highly relevant examples for the novel user.

What would be the relevant examples?
RL, RNN (reservoir), CNN, SOM, batch learning?
Anything else, anything less?

**Comment by Hananel-Hazan** [comment]
mnist/reservoir is functional (I update @sharath project) 
cifar10/cifar10_reservoir.py is next

**Comment by dee0512** [comment]
We planned on removing cifar10 examples.

**Comment by Ondrysak** [comment]
maybe a related issue https://github.com/BindsNET/bindsnet/issues/350 ?
