### ISSUE TITLE
More mathematical details about bindsnet.learning?

### ISSUE THREAD

**Issue by fangwei123456** [BindsNET/bindsnet#331]
I'm interested in bindsnet.learning. 
However, I can't find mathematical details (for example, a mathematical detail of simple Hebbian learning: Δw_ij = k * v_i * v_j) about the implement of  these learning rules in https://bindsnet-docs.readthedocs.io/bindsnet.learning.html.

**Comment by djsaunde** [comment]
Hm, looks like the BindsNET readthedocs page is broken; I'll look into this.
