### ISSUE TITLE
Monitor timestep

### ISSUE THREAD

**Issue by Pranav-Machingal** [BindsNET/bindsnet#340]
monitor doesn't seem to work for dt!=1.

are there any issues with
passing dt parameter to monitor and doing time=time/dt

**Comment by djsaunde** [comment]
Yeah, in general, `dt != 1` is not well-tested. I will try to take a look at this soon.

**Comment by djsaunde** [comment]
Could you please share example code that produces the error?

**Comment by Pranav-Machingal** [comment]
plot shows less number of spikes when `dt=0.1` as compared to `dt=1`
```
from bindsnet.models.models import TwoLayerNetwork
from bindsnet.encoding.encodings import poisson
from bindsnet.network.monitors import Monitor
import matplotlib.pyplot as plt
from bindsnet.analysis.plotting import plot_spikes
import torch

network = TwoLayerNetwork(n_inpt=4, n_neurons=2, dt=0.1)
source_monitor = Monitor(
    obj=network.layers["X"],
    state_vars=("s",),
    time=100,
)
network.add_monitor(monitor=source_monitor, name="X")

inpt_spikes = poisson(
    datum=torch.Tensor([200,50,100,150]), 
    time=100, dt=0.1
)

network.run(inpts={"X": inpt_spikes}, time=100)

spikes = {
    "X": source_monitor.get("s")
}

plt.ioff()
plot_spikes(spikes)
plt.show()
```

**Comment by khengyeww** [comment]
I have the same problem, and my current way of workaround is to use `int(time/dt)` for the `time` variable in `Monitor()`.
In this case: `source_monitor = Monitor( ... , time=int(100/0.1) )`.

I'm not sure if it's the right way but please update me on this too!
