### ISSUE TITLE
Minibatch for clamp/unclamp?

### ISSUE THREAD

**Issue by khengyeww** [BindsNET/bindsnet#342]
Hello, I'm currently trying out the minibatch feature.

In network.run() function, inputs takes the tensor shape of `[time, batch_size, *input_shape]`.
In my use case, I need to clamp certain neurons to spike according to each input. Thus, to use the minibatch feature I have generated shape of `[time, batch_size, n_neurons]` for the clamp dict (to follow the shape of inputs) and received below error.
```
   self.layers[l].s[:, clamp[t]] = 1
IndexError: too many indices for tensor of dimension 2
```
Is there a solution for this?

**Comment by djsaunde** [comment]
FYI, I am no longer contributing to this project. The BINDS lab version of this package is maintained [here](https://github.com/BINDS-LAB-UMASS/bindsnet).

**Comment by Hananel-Hazan** [comment]
Please share here the code to replicate this error
