### ISSUE TITLE
About running a SNN proposed by Diehl&CooK

### ISSUE THREAD

**Issue by lemonade117** [BindsNET/bindsnet#343]
Hi, I'm so glad to see your simulator. In your paper"BindsNET: A machine learning-oriented spiking neural networks library in Python", here is an example about running a SNN proposed by Diehl&CooK. I wonder did you use the brian simulator(Brian/Brian2?) and have you solve the problem that this SNN takes a lot of hours to trian?
Waiting for your help.

**Comment by Hananel-Hazan** [comment]
Yes, training the same model using BindsNET take less time
