### ISSUE TITLE
SparseConnection not finished

### ISSUE THREAD

**Issue by danielgafni** [BindsNET/bindsnet#344]
## Hello!

Could you please finish the implementation of SparseConnection with a learning rule?
Currently it’s not supported. As I understand, this is because sparse tensors and dense tensors behave differently in terms of code.
So that’s probably quite a lot of work. Can this be done by any chance, please?

It would also be nice to have sparse spikes. For example, inhibitor connections spikes that I’m working with now have sparsity around 0.002.
I’m sure that changing the type of these spikes to torch.sparse would make a huge boost in performance.
As I understand, currently PyTorch has no native way of multiplying two sparse tensors. So it’s just a suggestion for future.

It’s my first GitHub post, so feel free to tell me if I’m doing something wrong.

**Comment by Hananel-Hazan** [comment]
Hello Daniel,  thank you for using BindsNET and for your suggestions. You are right, supporting sparse tensors is now in a work in progress, as such, it will probably going to take some time to PyTorch team to fully support the necessary operations that are crucial for BindsNET.

Until them, you are welcome to help with pushing PR to the repository.

**Comment by danielgafni** [comment]
Currently I almost finished implementing SparseConnection for myself with scipy.sparse. 
Is this going to be useful for you right now?
I don't have any info yet about how much will this change affect learning speed in an actual network.
However for simply multiplying two matrices scipy.sparse.bsr_matrix is ~20 times faster than torch.FloatTensor (sparsity is 1/9).
I realize that at some point PyTorch is going to support sparse tensors completely, but is my solution good as a temporary option?

**Comment by Hananel-Hazan** [comment]
Thank you for offering to help.  I can certainly see the need to patching this weakness even if it a temporarily one. Your solution can definitely help until the PyTorch team will finish the development.
