### ISSUE TITLE
How could i use Gradient Descent on SNN?

### ISSUE THREAD

**Issue by ati6868** [BindsNET/bindsnet#348]
Hi
i am going to do Gradient Descent on MNIST , but i don't know the idea i am using , is correct  or not?
I use `network=Network(torch.nn.Module)` instead of only `network=Network()` and then i am using GD as below:
`criterion = torch.nn.MSELoss(reduction="sum")`
`model = network.run(inpts=inpts, time=time)`
`optimizer = torch.optim.SGD(model.parameters(), lr=1e-4, momentum=0.9)`
`optimizer.zero_grad()`
but when i'm running the code, i get this error:
`Traceback (most recent call last):
  File "C:\Users\Ati\Desktop\gd\GD - 3.py", line 147, in <module>
    update_interval=update_interval, max_prob=max_prob, train=train)`
`File "C:\Users\Ati\Desktop\gd\GD - 3.py", line 70, in main
    model = network.run(inpts=inpts, time=time)
  File "C:\python\Python37\lib\site-packages\bindsnet\network\network.py", line 332, in run`
`timesteps = int(time / self.dt)
TypeError: unsupported operand type(s) for /: 'int' and 'type' `

the way i am doing , is wrong?
I mean we can not `model = network.run(inpts=inpts, time=time)` and then use GD as have been said for artificial neural networks with torch?

**Comment by Hananel-Hazan** [comment]
I'm sorry, step function like spike is not differentiable, therefore GD method cannot work with spike base neurons.

**Comment by ati6868** [comment]
Thank you for response
But one example in experiment repo. Has been done about backpropagation
.... I think it's done with GD .... am i right ??????because i corrected
that code and now it's working for me

**Comment by Hananel-Hazan** [comment]
Yes, it does, but it use regular NN trained with GD, then the weights been copied to run the spiking NN
