### ISSUE TITLE
Locally Connected Spiking Neural Networks for Unsupervised Feature Learning

### ISSUE THREAD

**Issue by Ondrysak** [BindsNET/bindsnet#349]
I am trying to find a working example from paper below, where the experiments are claimed to be implemented in BindsNET, are there any plans to publish it here in form of an example, if not could you point me to a good starting point to replicate the results? 

https://arxiv.org/abs/1904.06269

**Comment by Hananel-Hazan** [comment]
Check this [link](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/conv_mnist.py).
