### ISSUE TITLE
Voltage plot of supervised_mnist.py -example has description the wrong way around

### ISSUE THREAD

**Issue by Danielle-Schuman** [BindsNET/bindsnet#352]
When you run supervised_mnist.py with --plot, the picture for the voltage has it's description "the wrong way around": It says "voltages for neurons (0 - [time]) from t = 0 to [n_neurons]".
E.g. if you run it with the default parameters – time = 500 and n_neurons = 100 – it says "voltages for neurons (0 - 500) from t = 0 to 100" (see attached picture).
I believe the cause of this to be that the method "plot_voltages" is expecting tensors of size [n_neurons, 1, time] (according to the variable naming in it), while it is being given tensors of the shape [time, 1, n_neurons] for the layers voltages. The size and naming of the axes of the plot seem to be correct, though.

![Plot_voltage_default_params](https://user-images.githubusercontent.com/52699523/74921209-b8ad7d00-53cd-11ea-895e-08bffec30a6b.png)

**Comment by Hananel-Hazan** [comment]
Thanks for finding this issue.
Can you confirm what version are you using? the pip version or the master?

**Comment by Danielle-Schuman** [comment]
I downloaded the code from this repository on February 6th and installed it with `pip install -e . `

**Comment by Hananel-Hazan** [comment]
Thank you for notice it, I update the plotting method #354
