### ISSUE TITLE
EnvironmentPipeline documentation

### ISSUE THREAD

**Issue by ferqui** [BindsNET/bindsnet#358]
Hi,
I'd like to ask if it could be possible to add to the documentation and example of how to use the EnvironmentPipeline. In the examples provides of the _breakout_, I would like to plot the spike activity of the layers, but it open an empty window. 
<img width="973" alt="Captura de pantalla 2020-03-09 a las 13 48 26" src="https://user-images.githubusercontent.com/11820464/76214417-fb17ec00-620c-11ea-9a59-72526861a24a.png">

Thanks a lot.
Best regards

**Comment by Hananel-Hazan** [comment]
Thank you for using BindsNET and for finding this. There are some ongoing efforts to address the documentation. Hopefully, that will improve in time. 
For the plotting issue, I push a fix. 
More improvements are on the way
