### ISSUE TITLE
AssertionError: Target dimensionality must be (out_channels, ?,(input_height - filter_height + 2 * padding_height) / stride_height + 1,(input_width - filter_width + 2 * padding_width) / stride_width + 1

### ISSUE THREAD

**Issue by tehreemnaqvi** [BindsNET/bindsnet#365]
Hi,
I am following your examples.I wanted to use convolutional layers in SNN. So, I followed your examples,which you have done for mnist.Currently, I am working on (two_conv.py) this code.
But i have some issue,when i run this code,got this error.
AssertionError: Target dimensionality must be (out_channels, ?,(input_height - filter_height + 2 * padding_height) / stride_height + 1,(input_width - filter_width + 2 * padding_width) / stride_width + 1
Although i changed this conv_layer_ = DiehlAndCookNodes(
    n=n_filters * total_conv_size, shape=(1, n_filters, *conv_size), refrac=0, traces=True, theta_decay=5e-1
) 
by 
conv_layer_ = DiehlAndCookNodes(
    n=n_filters * total_conv_size, shape=(n_filters, conv_size,conv_size), refrac=0, traces=True, theta_decay=5e-1
) 
But i got error that non-int tuples can't be multiply.
Please tell how can i fix this issue.
Thanks

**Comment by tehreemnaqvi** [comment]
When I changed the shape of output channels, i got this error.
n=n_filters * conv_size * conv_size, shape=(n_filters, conv_size, conv_size),
TypeError: can't multiply sequence by non-int of type 'tuple'

**Comment by Hananel-Hazan** [comment]
Thank you for bringing it up. The code that you mention is part of ongoing experiments done many versions ago. This code is not supported and not expected to work using the latest version.
