### ISSUE TITLE
Plotting Spikes, Voltages

### ISSUE THREAD

**Issue by tehreemnaqvi** [BindsNET/bindsnet#368]
Hi, I am trying to plot spikes,voltages.But once training is completed,I didn't get any plot.
This is my code:
 
    for epoch in range( args.n_epochs ):
        # Create a dataloader to iterate over dataset.
        dataloader = DataLoader(
            dataset,
            batch_size=args.batch_size,
            shuffle=True,
            num_workers=args.n_workers,
            pin_memory=args.gpu,
        )

        for step, batch in enumerate( tqdm( dataloader ) ):
            # Prep next input batch.
            inpts = {"I": batch["encoded_image"]}
            if args.gpu:
                inpts = {k: v.cuda() for k, v in inpts.items()}

            # Run the network on the input.
            network.run( inputs=inpts, time=args.time )

            # Plot simulation data.
            if args.plot:
                spikes = {}
                for name, monitor in network.monitors.items():
                    spikes[name] = monitor.get( "s" )[:, 0].view( args.time, -1 )

                spike_ims, spike_axes = plot_spikes(
                    spikes, ims=spike_ims, axes=spike_axes
                )

                #conv1_weights_im = plot_conv2d_weights(
                    #conv1_connection.w, im=conv1_weights_im, wmin=-1.0, wmax=1.0
                #)
                plot_conv2d_weights( conv1_connection.w, wmin=-1.0, wmax=1.0 )
                plt.savefig( '1.png' )
                plt.close()

                plot_conv2d_weights( conv2_connection.w, wmin=-1.0, wmax=1.0 )
                plt.savefig( '2.png' )
                plt.close()

                plot_weights( dense_connection.w, wmin=-1.0, wmax=1.0 )
                plt.savefig( '3.png' )
                plt.close()

                plot_weights( output_connection.w, wmin=-1.0, wmax=1.0 )
                plt.savefig( '4.png' )

                plt.show()
                plt.close()

                #conv2_weights_im = plot_conv2d_weights(
                    #conv2_connection.w, im=conv2_weights_im, wmin=-1.0, wmax=1.0
                #)
                #dense_weights_im = plot_weights(
                    #dense_connection.w, im=dense_weights_im, wmin=-1.0, wmax=1.0
                #)
               # output_weights_im = plot_weights(
                    #output_connection.w, im=output_weights_im, wmin=-1.0, wmax=1.0
                #)
                #plt.ioff()
               
                #plt.draw()
                #plt.pause(0.001)
                #plt.close()

        network.reset_state_variables()

**Comment by Danielle-Schuman** [comment]
Hi, 
So I had the same "issue" a while ago. Technically, this is not an issue, though, because the plots from plotting.py are not intended to be there after training, but for you to watch during training. For saving plots after training, there is the code in visualization.py. However, not all plots you can find in plotting.py are also in visualization.py. Since I also wanted to save the plots from plotting.py to look at after training, I modified the code the following way:
I wrote the following function into plotting.py:
`def save_plot(
    fig: Figure,
    directory: str,
    name: str,
    n: int
):
    file = directory + '/' + name + str(n)
    fig.savefig(file)`
which saves the figures to a specified directory, and then modified the plotting methods, making them return figures, e.g. for spikes and weights that would be:
`def plot_spikes(
    spikes: Dict[str, torch.Tensor],
    time: Optional[Tuple[int, int]] = None,
    n_neurons: Optional[Dict[str, Tuple[int, int]]] = None,
    ims: Optional[List[PathCollection]] = None,
    axes: Optional[Union[Axes, List[Axes]]] = None,
    figsize: Tuple[float, float] = (8.0, 4.5),
    fig: Figure = None
) -> Tuple[List[AxesImage], List[Axes], Figure]:
    # language=rst
    """
    Plot spikes for any group(s) of neurons.

    :param spikes: Mapping from layer names to spiking data. Spike data has shape
        ``[time, n_1, ..., n_k]``, where ``[n_1, ..., n_k]`` is the shape of the
        recorded layer.
    :param time: Plot spiking activity of neurons in the given time range. Default is
        entire simulation time.
    :param n_neurons: Plot spiking activity of neurons in the given range of neurons.
        Default is all neurons.
    :param ims: Used for re-drawing the plots.
    :param axes: Used for re-drawing the plots.
    :param figsize: Horizontal, vertical figure size in inches.
    :return: ``ims, axes``: Used for re-drawing the plots.
    """
    n_subplots = len(spikes.keys())
    if n_neurons is None:
        n_neurons = {}

    spikes = {k: v.view(v.size(0), -1) for (k, v) in spikes.items()}
    if time is None:
        # Set it for entire duration
        for key in spikes.keys():
            time = (0, spikes[key].shape[0])
            break

    # Use all neurons if no argument provided.
    for key, val in spikes.items():
        if key not in n_neurons.keys():
            n_neurons[key] = (0, val.shape[1])

    if ims is None:
        fig, axes = plt.subplots(n_subplots, 1, figsize=figsize)
        if n_subplots == 1:
            axes = [axes]

        ims = []
        for i, datum in enumerate(spikes.items()):
            spikes = (
                datum[1][
                    time[0] : time[1], n_neurons[datum[0]][0] : n_neurons[datum[0]][1]
                ]
                .detach()
                .clone()
                .cpu()
                .numpy()
            )
            ims.append(
                axes[i].scatter(
                    x=np.array(spikes.nonzero()).T[:, 0],
                    y=np.array(spikes.nonzero()).T[:, 1],
                    s=1,
                )
            )
            args = (
                datum[0],
                n_neurons[datum[0]][0],
                n_neurons[datum[0]][1],
                time[0],
                time[1],
            )
            axes[i].set_title(
                "%s spikes for neurons (%d - %d) from t = %d to %d " % args
            )
        for ax in axes:
            ax.set_aspect("auto")

        plt.setp(
            axes, xticks=[], yticks=[], xlabel="Simulation time", ylabel="Neuron index"
        )
        plt.tight_layout()
    else:
        for i, datum in enumerate(spikes.items()):
            spikes = (
                datum[1][
                    time[0] : time[1], n_neurons[datum[0]][0] : n_neurons[datum[0]][1]
                ]
                .detach()
                .clone()
                .cpu()
                .numpy()
            )
            ims[i].set_offsets(np.array(spikes.nonzero()).T)
            args = (
                datum[0],
                n_neurons[datum[0]][0],
                n_neurons[datum[0]][1],
                time[0],
                time[1],
            )
            axes[i].set_title(
                "%s spikes for neurons (%d - %d) from t = %d to %d " % args
            )

    plt.draw()

    return ims, axes, fig


def plot_weights(
    weights: torch.Tensor,
    wmin: Optional[float] = 0,
    wmax: Optional[float] = 1,
    im: Optional[AxesImage] = None,
    figsize: Tuple[int, int] = (5, 5),
    cmap: str = "hot_r",
    fig: Figure = None
) -> Tuple[AxesImage, Figure]:
    # language=rst
    """
    Plot a connection weight matrix.

    :param weights: Weight matrix of ``Connection`` object.
    :param wmin: Minimum allowed weight value.
    :param wmax: Maximum allowed weight value.
    :param im: Used for re-drawing the weights plot.
    :param figsize: Horizontal, vertical figure size in inches.
    :param cmap: Matplotlib colormap.
    :return: ``AxesImage`` for re-drawing the weights plot.
    """
    local_weights = weights.detach().clone().cpu().numpy()
    if not im:
        fig, ax = plt.subplots(figsize=figsize)

        im = ax.imshow(local_weights, cmap=cmap, vmin=wmin, vmax=wmax)
        div = make_axes_locatable(ax)
        cax = div.append_axes("right", size="5%", pad=0.05)

        ax.set_xticks(())
        ax.set_yticks(())
        ax.set_aspect("auto")

        plt.colorbar(im, cax=cax)
        fig.tight_layout()
    else:
        im.set_data(local_weights)

    return im, fig`
and then I called them in my main program – to which I passed a directory to save the plots in as a command line argument – the following way:
`spike_ims, spike_axes, spike_fig = plot_spikes(
            {layer: spikes[layer].get("s").view(time, 1, -1) for layer in spikes},
            ims=spike_ims,
            axes=spike_axes,
            fig=spike_fig
        )
  save_plot(fig=spike_fig, directory=directory, name="spikes", n=i)
  weights_im, weights_fig = plot_weights(square_weights, im=weights_im, fig=weights_fig)
  save_plot(fig=weights_fig, directory=directory, name="weights", n=i)`
Maybe you could do it a similar way, I hope this helps...
P.S. I'm not one of the scientists developing the BindsNET library, this is just "peer-to-peer" help ;)

**Comment by tehreemnaqvi** [comment]
Thank you very much for your help.

**Comment by Danielle-Schuman** [comment]
You're welcome :)

**Comment by tehreemnaqvi** [comment]
Mam ,the above save plot is giving error like this:
![save_plot](https://user-images.githubusercontent.com/38427571/81559837-21a00200-93cb-11ea-9834-68b15f54f68f.PNG)

**Comment by Danielle-Schuman** [comment]
Oh, I guess I forgot to mention the import statement:
`from matplotlib.figure import Figure`

**Comment by tehreemnaqvi** [comment]
Yeah it's working.
Mam, below every plot function, I have to call fig :Figure =None??

**Comment by Danielle-Schuman** [comment]
That's nice to hear :)
I'm not sure whether you need fig :Figure =None . How about you just try it out by running a small example with or without? Then you'll see what works and what doesn't...

**Comment by tehreemnaqvi** [comment]
Okay Mam.
Thank you.

**Comment by tehreemnaqvi** [comment]
Mam, didn't get any plot.
This is my code:

**Comment by Danielle-Schuman** [comment]
I can't see your code, it just says "..." and then shows part of an E-Mail ... Could you post it again?
Also: I thought you said earlier that it worked?

Anyways: Did you provide a directory path at the appropriate point(s) in the code? (e.g. I included a command line argument for it that I then write to the variable "directory" in my code...) If not, that might be the problem because that would be the place where the plots are saved (as .png-files)...

**Comment by tehreemnaqvi** [comment]
Mam this my full code:
"""
Attempt to replicate the network and unsupervised training procedure from "Training Deep
Spiking Convolutional Neural Networks With STDP-Based Unsupervised Pre-training Followed
by Supervised Fine-Tuning"
(https://www.frontiersin.org/articles/10.3389/fnins.2018.00435/full). They use a layer-
wise pre-training scheme, which is not yet implemented in this script.
"""

import os
import argparse
from abc import ABC

import torch
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import torch.nn.functional as F
from tqdm import tqdm
from torchvision import transforms
from matplotlib.figure import Figure

import bindsnet
from bindsnet.utils import im2col_indices
from bindsnet.encoding import PoissonEncoder
from bindsnet.network.monitors import Monitor
from bindsnet.datasets import DataLoader, MNIST
from bindsnet.network.nodes import Input, LIFNodes
from bindsnet.network.topology import Conv2dConnection, Connection
from bindsnet.analysis.plotting import plot_spikes, plot_conv2d_weights, plot_weights

matplotlib.use( "Qt5Agg" )


def save_plot(
        fig: Figure, directory: str, name: str, n: int):
    file = directory + '/' + name + str( n )
    fig.savefig( file )


class WeightDependentPost( bindsnet.learning.LearningRule ):
    def __init__(self, connection, nu=None, reduction=None, weight_decay=0.0, **kwargs):
        super().__init__(
            connection=connection,
            nu=nu,
            reduction=reduction,
            weight_decay=weight_decay,
            **kwargs,
        )

        assert self.source.traces, "Pre-synaptic nodes must record spike traces."
        assert (
                connection.wmin != -np.inf and connection.wmax != np.inf
        ), "Connection must define finite wmin and wmax."

        self.wmin = connection.wmin
        self.wmax = connection.wmax

        if isinstance( connection, Connection ):
            self.update = self._connection_update
        elif isinstance( connection, Conv2dConnection ):
            self.update = self._conv2d_connection_update
        else:
            raise NotImplementedError(
                "This learning rule is not supported for this Connection type."
            )

        self.x_offset = kwargs.get( "x_offset", 0.2 )

    def _connection_update(self, **kwargs) -> None:
        batch_size = self.source.batch_size

        source_x = self.source.x.view( batch_size, -1 ).unsqueeze( 2 )
        target_s = self.target.s.view( batch_size, -1 ).unsqueeze( 1 ).float()

        update = 0

        # Post-synaptic update.
        if self.nu[1]:
            post = self.reduction( torch.bmm( source_x, target_s ), dim=0 )
            update = (
                    self.nu[1] * (post - self.x_offset) * (self.wmax - self.connection.w)
            )

        self.connection.w += update

        super().update()

    def _conv2d_connection_update(self, **kwargs) -> None:
        # Get convolutional layer parameters.
        (
            out_channels,
            in_channels,
            kernel_height,
            kernel_width,
        ) = self.connection.w.size()
        padding, stride = self.connection.padding, self.connection.stride
        batch_size = self.source.batch_size

        # Reshaping spike traces and spike occurrences.
        source_x = im2col_indices(
            self.source.x, kernel_height, kernel_width, padding=padding, stride=stride
        )
        target_s = self.target.s.view( batch_size, out_channels, -1 ).float()

        update = 0

        # Post-synaptic update.
        if self.nu[1]:
            post = self.reduction(
                torch.bmm( target_s, source_x.permute( (0, 2, 1) ) ), dim=0
            ).view( self.connection.w.size() )
            update += (
                    self.nu[1]
                    * (post - self.x_offset)
                    * (self.connection.w - self.wmin)
                    * (self.wmax - self.connection.wmin)
            )

        self.connection.w += update

        super().update()


class SpatialPooling2dConnection( bindsnet.network.topology.AbstractConnection ):
    def reset_state_variables(self) -> None:
        pass

    def __init__(
            self,
            source,
            target,
            kernel_size,
            stride,
            nu=None,
            reduction=None,
            weight_decay=0.0,
            **kwargs,
    ):
        super().__init__( source, target, nu, reduction, weight_decay, **kwargs )

        self.kernel_size = kernel_size
        self.stride = stride

    def compute(self, s):
        pooled = F.avg_pool2d(
            s.float(), kernel_size=self.kernel_size, stride=self.stride
        )
        return (pooled >= 0.8).float()

    def update(self, **kwargs):
        pass

    def reset_(self):
        pass

    def normalize(self):
        pass


class PassThroughNodes( bindsnet.network.nodes.Nodes ):
    def __init__(
            self,
            n=None,
            shape=None,
            traces=False,
            traces_additive=False,
            tc_trace=5e-2,
            trace_scale=1.0,
            sum_input=False,
    ):
        super().__init__(
            n=n,
            shape=shape,
            traces=traces,
            traces_additive=traces_additive,
            tc_trace=tc_trace,
            trace_scale=trace_scale,
            sum_input=sum_input,
        )

    def forward(self, x: torch.Tensor):
        self.s = x

    def reset_(self):
        self.s.zero_()


directory = '/Users/Tehreem/PycharmProjects/qasim/bindsnet-master/bindsnet-master/snn-minibatch-master/minibatch/'


def main(args):
    # Random seed.
    if args.gpu and torch.cuda.is_available():
        torch.cuda.manual_seed_all( args.seed )
    else:
        torch.manual_seed( args.seed )

    # Determines number of workers.
    if args.n_workers == -1:
        args.n_workers = args.gpu * 4 * torch.cuda.device_count()

    # Build network.
    network = bindsnet.network.Network( dt=args.dt, batch_size=args.batch_size )

    # Layers.
    input_layer = Input( shape=(1, 28, 28), traces=True )
    conv1_layer = LIFNodes( shape=(20, 24, 24), traces=True )
    pool1_layer = PassThroughNodes( shape=(20, 12, 12), traces=True )
    conv2_layer = LIFNodes( shape=(50, 8, 8), traces=True )
    pool2_layer = PassThroughNodes( shape=(50, 4, 4), traces=True )
    dense_layer = LIFNodes( shape=(200,), traces=True )
    output_layer = LIFNodes( shape=(10,), traces=True )

    network.add_layer( input_layer, name="I" )
    network.add_layer( conv1_layer, name="C1" )
    network.add_layer( pool1_layer, name="P1" )
    network.add_layer( conv2_layer, name="C2" )
    network.add_layer( pool2_layer, name="P2" )
    network.add_layer( dense_layer, name="D" )
    network.add_layer( output_layer, name="O" )

    # Connections.
    conv1_connection = Conv2dConnection(
        source=input_layer,
        target=conv1_layer,
        update_rule=WeightDependentPost,
        nu=(0.0, args.nu),
        kernel_size=5,
        stride=1,
        wmin=-1.0,
        wmax=1.0,
    )
    pool1_connection = SpatialPooling2dConnection(
        source=conv1_layer, target=pool1_layer, kernel_size=2, stride=2
    )
    conv2_connection = Conv2dConnection(
        source=pool1_layer,
        target=conv2_layer,
        update_rule=WeightDependentPost,
        nu=(0.0, args.nu),
        kernel_size=5,
        stride=1,
        wmin=-1.0,
        wmax=1.0,
    )
    pool2_connection = SpatialPooling2dConnection(
        source=conv2_layer, target=pool2_layer, kernel_size=2, stride=2
    )
    dense_connection = Connection(
        source=pool2_layer,
        target=dense_layer,
        update_rule=WeightDependentPost,
        nu=(0.0, args.nu),
        wmin=-1.0,
        wmax=1.0,
    )
    output_connection = Connection(
        source=dense_layer,
        target=output_layer,
        update_rule=WeightDependentPost,
        nu=(0.0, args.nu),
        wmin=-1.0,
        wmax=1.0,
    )

    network.add_connection( connection=conv1_connection, source="I", target="C1" )
    network.add_connection( connection=pool1_connection, source="C1", target="P1" )
    network.add_connection( connection=conv2_connection, source="P1", target="C2" )
    network.add_connection( connection=pool2_connection, source="C2", target="P2" )
    network.add_connection( connection=dense_connection, source="P2", target="D" )
    network.add_connection( connection=output_connection, source="D", target="O" )

    # Monitors.
    for name, layer in network.layers.items():
        monitor = Monitor( obj=layer, state_vars=("s",), time=args.time )
        network.add_monitor( monitor=monitor, name=name )

    # Directs network to GPU.
    if args.gpu:
        network.to( "cuda" )

    # Load MNIST data.
    dataset = MNIST(
        PoissonEncoder( time=args.time, dt=args.dt ),
        None,
        root=os.path.join( bindsnet.ROOT_DIR, "data", "MNIST" ),
        download=True,
        transform=transforms.Compose(
            [transforms.ToTensor(), transforms.Lambda( lambda x: x * args.intensity )]
        ),
    )

    spike_ims = None
    spike_axes = None
    conv1_weights_im = None
    conv2_weights_im = None
    dense_weights_im = None
    output_weights_im = None

    for epoch in range( args.n_epochs ):
        # Create a dataloader to iterate over dataset.
        dataloader = DataLoader(
            dataset,
            batch_size=args.batch_size,
            shuffle=True,
            num_workers=args.n_workers,
            pin_memory=args.gpu,
        )

        for step, batch in enumerate( tqdm( dataloader ) ):
            # Prep next input batch.
            inpts = {"I": batch["encoded_image"]}
            if args.gpu:
                inpts = {k: v.cuda() for k, v in inpts.items()}

            # Run the network on the input.
            network.run( inputs=inpts, time=args.time )

            # Plot simulation data.
            if args.plot:
                spikes = {}
                for name, monitor in network.monitors.items():
                    spikes[name] = monitor.get( "s" )[:, 0].view( args.time, -1 )

                spike_ims, spike_axes, spike_fig = plot_spikes(
                    {layer: spikes[layer].get( "s" ).view( time, 1, -1 ) for layer in spikes},
                    ims=spike_ims,
                    axes=spike_axes,
                    fig=spike_fig
                )
                save_plot( fig=spike_fig, directory=directory, name="spikes", n=1 )

                weights_im, weights_fig = plot_weights( dense_connection.w, im=weights_im, fig=weights_fig )
                save_plot( fig=weights_fig, directory=directory, name="weights", n=1 )

                # conv1_weights_im = plot_conv2d_weights(
                # conv1_connection.w, im=conv1_weights_im, wmin=-1.0, wmax=1.0
                # )
                #plot_conv2d_weights( conv1_connection.w, wmin=-1.0, wmax=1.0 )
                #plt.savefig( '1.png' )
                #plt.draw()
                # plt.show()
                # plt.pause( 0.001 )
                #plt.close()

                #plot_conv2d_weights( conv2_connection.w, wmin=-1.0, wmax=1.0 )
                #plt.savefig( '2.png' )
                #plt.draw()
                # plt.show()
                # plt.pause( 0.001 )
                #plt.close()

                #plot_weights( dense_connection.w, wmin=-1.0, wmax=1.0 )
                #plt.savefig( '3.png' )
                #plt.draw()
                # plt.show()
                # plt.pause( 0.001 )
                #plt.close()

                #plot_weights( output_connection.w, wmin=-1.0, wmax=1.0 )
                #plt.savefig( '4.png' )
               # plt.draw()

                # plt.pause( 0.001 )

                # plt.show()
                # plt.pause( 0.001 )
                # plt.show()
                plt.close()

                # conv2_weights_im = plot_conv2d_weights(
                # conv2_connection.w, im=conv2_weights_im, wmin=-1.0, wmax=1.0
                # )
                # dense_weights_im = plot_weights(
                # dense_connection.w, im=dense_weights_im, wmin=-1.0, wmax=1.0
                # )
            # output_weights_im = plot_weights(
            # output_connection.w, im=output_weights_im, wmin=-1.0, wmax=1.0
            # )
            # plt.ioff()

            # plt.draw()

            # plt.close()

            network.reset_state_variables()


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument( "--seed", type=int, default=0 )
    parser.add_argument( "--batch-size", type=int, default=8 )
    parser.add_argument( "--n-epochs", type=int, default=1 )
    parser.add_argument( "--dt", type=float, default=1.0 )
    parser.add_argument( "--time", type=int, default=25 )
    parser.add_argument( "--intensity", type=int, default=128 )
    parser.add_argument( "--nu", type=float, default=1e-4 )
    parser.add_argument( "--n-workers", type=int, default=-1 )
    parser.add_argument( "--gpu", action="store_true" )
    parser.add_argument( "--plot", action="store_true" )
    return parser.parse_args()


args = parse_args()

seed = args.seed
n_epochs = args.n_epochs
# n_test = args.n_test
# kernel_size = args.kernel_size
# stride = args.stride
# n_filters = args.n_filters
# padding = args.padding
time = args.time
dt = args.dt
intensity = args.intensity
# progress_interval = args.progress_interval
# update_interval = args.update_interval
# train = args.train
plot = args.plot
gpu = args.gpu

if __name__ == "__main__":
    main( parse_args() )

**Comment by tehreemnaqvi** [comment]
![directory](https://user-images.githubusercontent.com/38427571/81580066-e95aec80-93e7-11ea-92d9-852ce030237d.PNG)

**Comment by tehreemnaqvi** [comment]
This is what i plotted but plot didn't save:
![plotting](https://user-images.githubusercontent.com/38427571/81580269-30e17880-93e8-11ea-95fc-6caf615bf454.PNG)

**Comment by tehreemnaqvi** [comment]
Like this:
**directory = '/Users/Tehreem/PycharmProjects/qasim/bindsnet-master/bindsnet-master/snn-minibatch-master/minibatch/*.png'**

**Comment by Danielle-Schuman** [comment]
So first of all: Have you modified the code in plotting.py to return the figures (because usually, it just returns the axes and ims, not fig)? (And did you import Figure there, too, doing so?)
If that works correctly, I'm not sure where your problem is either, I'm sorry.
I think the way you specified your directory (without *.png) should be fine, by the way ...

Anyway, if you're interested, you can find my modified code in its entirety at:
- https://github.com/Danielle-Schuman/bindsnetQA/blob/master/examples/mnist/supervised_mnist.py (This is my "main", where I modified supervised_mnist.py)
and 
- https://github.com/Danielle-Schuman/bindsnetQA/blob/master/bindsnet_qa/analysis/plotting.py (Here the modified plotting.py. I did not modify all plotting methods, e.g. not plot_conv2d_weights, only the ones I needed for my project, i.e. the ones I call in the module in the first link)
(By the way: My project is all about trying out a different way of calculating in network.run(...), so that's different, too, there, but that doesn't impact the plotting, since the outputs are the same. So just ignore that part.)

I wish you good luck!

**Comment by tehreemnaqvi** [comment]
Thank you very much.
