### ISSUE TITLE
 network.save( os.path.join( params_path, model_name + '.pt' ) )

### ISSUE THREAD

**Issue by tehreemnaqvi** [BindsNET/bindsnet#371]
Hi, 
1. I am following your code "**diehl_and_cook_2015.py**".When I run this code. I got this error:

 **No such file or directory: '/Users/Tehreem/PycharmProjects/bindsnet_experiments-master/experiments1/mnist/params/mnist/conv/.pt'**
I don't know what's the problem with this?

2. For testing mode, we just need to to change test = True in this line:
  **parser.set_defaults( plot=False, gpu=False, Train=True )**

Thanks

**Comment by Hananel-Hazan** [comment]
Hi,
Thank you for bringing this up.

The script that you are using is an old unsupported script that been use in testing stages. 
Please use the script `eth_mnist.py` [here ](https://github.com/BindsNET/bindsnet/tree/master/examples/mnist).
If you have improvements or suggestions please feel free to submit a pull request. 

Thanks and happy spiking

**Comment by tehreemnaqvi** [comment]
Thanks for your reply.
I wanna ask one more thing, that for the testing phase we just have to do like this:
**parser.set_defaults(plot=False, gpu=False, test=True)**

Thanks

**Comment by Hananel-Hazan** [comment]
Thank you for pointing it out. 
Sadly, the code for the testing phase is not present in the example. So the test=True has no meaning at the moment. 
You can use the existing code to write the testing function.  
In any case, this oversite will be fixed in the future.
