### ISSUE TITLE
Synaptic current decay. But what are traces?

### ISSUE THREAD

**Issue by webstorms** [BindsNET/bindsnet#377]
Hi,

I am trying to figure out how to implement the current-based synapse model i.e. decaying current. I see the implementation of `CurrentLIFNodes`, which I assume is what I am looking for. However I am now confused by the trace parameters in the Node class (which I initially thought controlled this behaviour). Could someone please elaborate on the following parameters.
```
        :param traces: Whether to record decaying spike traces.
        :param traces_additive: Whether to record spike traces additively.
        :param tc_trace: Time constant of spike trace decay.
        :param trace_scale: Scaling factor for spike trace.
        :param sum_input: Whether to sum all inputs.
```

Thanks!

**Comment by Hananel-Hazan** [comment]
The `CurrentLIFNodes` neuron implemented from Professor Wulfram Gerstner website, [here](https://web.archive.org/web/20190517172145/http://icwww.epfl.ch/%7Egerstner/SPNM/node26.html#SECTION02313000000000000000) you can find all the details. 
The descriptions in the code are almost self-explanatory. 
If you have a specific question please don't hesitate to ask.  But, please try to play around with the parameters and follow the code, using your favorite debugger.  If you find the explanation lucking, please suggest an alternative and submit PR.
