### ISSUE TITLE
Node Type

### ISSUE THREAD

**Issue by XDUSPONGE** [BindsNET/bindsnet#380]
hello for the Node these code released is the simple lif neuron
tau dv/dt = -(V - V_rest)
however in the diehl's paper, it uses ge and gi in the computation
So why the DiehlNode does not have these two dynamic conductance

**Comment by Hananel-Hazan** [comment]
Hi, thanks for using BindsNET. 
The DiehlAndCookNodes is a modified version that been adapted for BindsNET and changes to be more general.  
The use of separate conductances for excitatory and inhibitory was relevant to demonstrate the model in their paper, which had excitatory and inhibitory layers. It is not however relevant to be used as a general layer in BindsNET.  In essence, both models should behave the same.
