### ISSUE TITLE
Showing the saved confusion matrix

### ISSUE THREAD

**Issue by rachmadvwp** [BindsNET/bindsnet#382]
Hi,
Just want to ask, how can we show/plot the saved confusion matrix?
I saved it using the following excerpt, from this [sample](https://github.com/BINDS-LAB-UMASS/bindsnet_experiments/blob/8a20be9d1ede021b70ff95cc7e85024ff5a222db/experiments/mnist/diehl_and_cook_2015.py#L305)

```
    # Compute confusion matrices and save them to disk.
    confusions = {}
    for scheme in predictions:
        confusions[scheme] = confusion_matrix(labels, predictions[scheme])

    to_write = ['train'] + params if train else ['test'] + test_params
    f = '_'.join([str(x) for x in to_write]) + '.pt'
    torch.save(confusions, os.path.join(confusion_path, f))
```
Thanks in advance

**Comment by Hananel-Hazan** [comment]
The unsupported example use the confusion matrices function from scikit-learn.
To show the confusion matrix use `print(confusions)`
For more information about the confusion matrices function please see the scikit-learn page [here ](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html)and [here](https://scikit-learn.org/stable/auto_examples/semi_supervised/plot_label_propagation_digits.html#sphx-glr-auto-examples-semi-supervised-plot-label-propagation-digits-py)

**Comment by rachmadvwp** [comment]
Hi, 
From the same sample, I run it perfectly on cpu but faced error when running on cuda gpu, which points to:
```
# Save results to disk.
    results = [
        np.mean(curves['all']), np.mean(curves['proportion']), np.mean(curves['ngram']),
        np.max(curves['all']), np.max(curves['proportion']), np.max(curves['ngram'])
    ]
```
with error message:
```
np.mean(curves['all']), np.mean(curves['proportion']), np.mean(curves['ngram']),
  File "../anaconda3/envs/BindsNET/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 3118, in mean
    out=out, **kwargs)
  File "../anaconda3/envs/BindsNET/lib/python3.7/site-packages/numpy/core/_methods.py", line 85, in _mean
    ret = ret.dtype.type(ret / rcount)
AttributeError: 'torch.dtype' object has no attribute 'type'
```
Could you please show the way how to solve this.
Thanks in advance.

**Comment by Hananel-Hazan** [comment]
Try to use `.cpu().numpy()` on those variables.

**Comment by rachmadvwp** [comment]
I'll try this first and let you know if it doesn't work out.

**Comment by rachmadvwp** [comment]
It gets this error now

Traceback (most recent call last):
  File "main.py", line 416, in <module>
    main(**args)
  File "main.py", line 327, in main
    np.mean(curves['all'].cpu().numpy()), np.mean(curves['proportion'].cpu().numpy()), np.mean(curves['ngram'].cpu().numpy()),
AttributeError: 'list' object has no attribute 'cpu'

**Comment by rachmadvwp** [comment]
I have solved the above problem.

Now, I have another one, from the same sample when running it on cuda gpu

```
for scheme in predictions:
        confusions[scheme] = confusion_matrix(labels, predictions[scheme])
```

It gives me error

`TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`

I have tried `.cpu()`, `.cpu().numpy()`, and `np.array(...)`. But none of them work.
Could you please show me how to solve it?

Thanks in advance.

**Comment by Hananel-Hazan** [comment]
I'm sorry, we are not supporting this old script, please use [this ](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/eth_mnist.py)script instead.
