### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by Adam-Antios** [BindsNET/bindsnet#390]
Hello! I am trying to use BindsNET but I find that the documentation is practically non-existent. There is a pdf file with some initial
setup but apart from that nothing else. Moreover the code that exists in the paper 

"BindsNET: A machine learning-oriented spiking neural networks library in Python"

produces mistakes when I try to run it and thus it is not helpful. On top of that this code doesn't even exist in any source which you can copy and paste and thus one has to write it from the start.

**Comment by SimonInParis** [comment]
Hi.

Here are the documentation:
https://bindsnet-docs.readthedocs.io/
I hope it will be helpful to you.
Remember BindsNet is still under heavy development.

You can read the example source codes, as they contain everything you need
to build, monitor and diagnose your own networks.
You can start with the eth_mnist.py
<https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/eth_mnist.py>
which is quite simple.

Hope it helps !
Thanks for your interest.
Simon Caby

Le ven. 3 juil. 2020 à 09:17, Adam-Antios <notifications@github.com> a
écrit :

**Comment by Adam-Antios** [comment]
Well obviously I have read this material. Actually this is the only kind of information that currently exist and it doesn't cover anything apart from the most basic of operations. I think that the developers need to improve the documentation as soon as possible or no one will be able to use Bindsnet.

**Comment by Hananel-Hazan** [comment]
Thank you for your comment, your opinion is very important for us. 
Please explain what would help you to start programming using BindsNET?
Also, please elaborate on what missing from your perspective as a novel user in the current documentation and examples.

**Comment by Adam-Antios** [comment]
Thank you for the quick response. First of all I felt like there exists a basic introduction as to how to start building a network but after that the user is left on its own. To be more specific:

- Because I am not just trying to implement machine learning algorithms, but I am also interested in the spiking neural networks' inner workings and their close relationship with computational neuroscience, I started by reading the published paper and trying running the examples presented there. Let me start by saying that those code examples should be located somewhere so readers could copy and paste them as it is a cumbersome process to have to write them line by line, which also leads to errors if you make a typo. Moreover and most importantly when I tried those examples I faced huge issues as they wouldn't run. When you google Bindsnet or Spiking Neural networks in PyTorch the published paper is very prominently presented in the results so ts examples should be easily copied and successfully deployed.

- There should exist step-by-step tutorials on various tasks with Bindsnet so new users can follow them and understand its operation. As an example, Nengo has a very nice structure in its examples, which cover a lot of topics.

- There must be a clear explanation of the various parts of Bindsnet. For example today I tried to find a description of `NetworkPipeline` but there was no information in the documentation. I had to dug into the code, which led to having to search and connect multiple parts of multiple files, which is not ideal when you try to prototype something quickly.

Something that is not tied to the documentation per se but a general comment, is that even now I am not really sure as to how active is the development of Bindsnet and whether a roadmap regarding this development exists. For example Nengo or NEST have news about newer versions and future milestones, but I haven't managed to find anything specific about Bindsnet. When someone develops in a specific framework you want to know how viable it is.

**Comment by Hananel-Hazan** [comment]
Thank you for your feedback, it is very useful. If you have an interest in spiking neurons, machine learning, and neuroscience you came to the right place. 

You have provided ample food for thought and the critique benefits the research community.  We would be happy to incorporate your step by step guide to the available resources for BindsNET so that we can add to the repertoire of resources for all users.
