### ISSUE TITLE
How to construct an attention model based on bindsnet?

### ISSUE THREAD

**Issue by wbzhang233** [BindsNET/bindsnet#391]
Hello! I am doing research about midbrain network now, I want to construct an attention model based on bindsnet, but I can't find any example. What is  the workflow of doing so? PLS.

**Comment by Hananel-Hazan** [comment]
Thank you for using BindsNET. 
Can you share your example or paper describes the network you would like to build?

The workflow of learning and using BindsNET is by example. Use the code in the [examples directory](https://github.com/BindsNET/bindsnet/tree/master/examples) to build your network. For help on each function use the [documentations](https://bindsnet-docs.readthedocs.io/)

Good Luck
