### ISSUE TITLE
about example/mnist/supervised_mnist.py

### ISSUE THREAD

**Issue by daiminghuan** [BindsNET/bindsnet#394]
![image](https://user-images.githubusercontent.com/51187217/87776152-e5b96b00-c859-11ea-8db1-df81af6cdaae.png)

 Accuracy: 0.0959040959040959: 1001it [08:10,  2.04it/s]  

Is the accuracy of the example so low? 
I'm not so sure

**Comment by Hananel-Hazan** [comment]
Thank you for posting this issue. 
Can you elaborate on what version of BindsNET do you use? What parameters do you use to achieve this low accuracy?
Please look at  #362 the example with the default values should give you more then 60%

**Comment by daiminghuan** [comment]
thank you!&nbsp; I've got the new version of bindsnet ，it worked !



---Original---
