### ISSUE TITLE
Breakout example only works when forcing CPU

### ISSUE THREAD

**Issue by wnourse05** [BindsNET/bindsnet#395]
I've tried running the breakout example in version 0.2.7, but I can only get it to work by exporting the shell variable `CUDA_VISIBLE_DEVICES=""` and forcing the CPU. If I try to run with the GPU, I get the following error:

> Traceback (most recent call last):
>   File "/home/will/bindsnet/examples/breakout/breakout.py", line 53, in <module>
>     pipeline.step(result)
>   File "/home/will/bindsnet/bindsnet/pipeline/base_pipeline.py", line 124, in step
>     step_out = self.step_(batch, **kwargs)
>   File "/home/will/bindsnet/bindsnet/pipeline/environment_pipeline.py", line 266, in step_
>     self.network.run(inputs=inputs, time=self.time, reward=reward, **kwargs)
>   File "/home/will/bindsnet/bindsnet/network/network.py", line 357, in run
>     self.layers[l].forward(x=current_inputs[l])
>   File "/home/will/bindsnet/bindsnet/network/nodes.py", line 220, in forward
>     super().forward(x)
>   File "/home/will/bindsnet/bindsnet/network/nodes.py", line 104, in forward
>     self.x.masked_fill_(self.s != 0, 1)
> RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mask' in call to _th_masked_fill_bool_

I've tried forcing it onto the GPU using`torch.cuda.set_device("cuda:0")` and `network.to("cuda:0")` to no avail. How can I get this to work using the GPU?

**Comment by Hananel-Hazan** [comment]
Thank you for using BindsNET. 
Can you elaborate on your setup, where do you add the shell variable?

The script `breakout.py` don't have parameter to choose between CPU to GPU, and it runs on my computer using CPU without any issue

**Comment by wnourse05** [comment]
My setup is a GTX 980 Ti and Ubuntu 20.04, running in a python 3.8.2 venv with only bindsnet and its dependencies. When I run `breakout.py` (or `breakout_stdp.py`) from the terminal, I get the errors shown above. When I force the torch backend to use only the CPU, by entering `export CUDA_VISIBLE_DEVICES=""` into the terminal first before running `breakout.py`, then the script works.

Using just the CPU I can get it to work, but only by telling torch that there isn't a GPU. I'm trying to use this as a reference for building a much larger model that will need the GPU, so I've tried adding lines from other scripts which work to try and get all of the tensors on the same device. It just seems like somewhere tensors are getting only sent to the CPU, even if everything else uses the GPU.

How can I successfully modify this script to use the GPU, not the CPU? If the methodology in this script is not amenable to running on a GPU,is there a different process for RL in bindsnet? These scripts are the only examples provided.

**Comment by Hananel-Hazan** [comment]
Please run the following code on your system with a default setting, without set `export CUDA_VISIBLE_DEVICES=""` 
```
import os
import torch
import time
import sys

print(os.environ)
print(torch.cuda.device_count())
print(torch.cuda.current_device())
print(os.getpid())
sys.stdout.flush()

device = torch.device('cuda')
a = torch.randn(2, 2, device=device)

os.system('nvidia-smi')
```

Also, What is your system default settings of `CUDA_VISIBLE_DEVICES` ?

Using `network.to("cuda")`  and adding the parameter `device='cuda'` in `EnvironmentPipeline` is the correct way to use the GPU. 

The methodology of running RL on the GPU is a little bit tricky. Typically, you would like to put your network and all the training data on GPU. This will give you the best performance. But, in the RL case, this could be a problem for two reasons.

1. The RL training data is usually bigger than your GPU memory capacity.  The only solution is to put all the data on the CPU and transfer chunks to the GPU for training. This way reduces performance. But, you can alleviate the situation by using threading for the memory move. The memory moves are not implemented yet in BindsNET (PyTorch use similar mechanism). 
2. The simulator (ATARI, gym, etc ) usually runs and uses CPU and not GPU. Therefore the data need to be transferred in any case.

**Comment by SimonInParis** [comment]
Some learning parameters are not located on GPU.

Step 1.
In **breakout_stdp.py,** don't forget to add     **device='cuda'** when calling **environment_pipeline = EnvironmentPipeline()**


Step 2.
As a quick fix, you can make this small changes in bindsnet/learning/learning.py:
lines from 549:

        if not hasattr(self, "p_plus"):
            self.p_plus = torch.zeros(batch_size, *self.source.shape)
        if not hasattr(self, "p_minus"):
            self.p_minus = torch.zeros(batch_size, *self.target.shape)
        if not hasattr(self, "eligibility"):
            self.eligibility = torch.zeros(batch_size, *self.connection.w.shape)

to :

        if not hasattr(self, "p_plus"):
            self.p_plus = torch.zeros(batch_size, *self.source.shape, device=self.source.s.device)
        if not hasattr(self, "p_minus"):
            self.p_minus = torch.zeros(batch_size, *self.target.shape, device=self.source.s.device)
        if not hasattr(self, "eligibility"):
            self.eligibility = torch.zeros(batch_size, *self.connection.w.shape, device=self.source.s.device)


Sorry for this GPU bug. 
Should work fine now.

**Comment by wnourse05** [comment]
These changes fixed the issue for me, thank you.
