### ISSUE TITLE
When I run the SOM_LM_SNN example, an error occurred

### ISSUE THREAD

**Issue by CHonChou** [BindsNET/bindsnet#397]
File "/home/answer/bindsnet/bindsnet-master/examples/mnist/SOM_LM-SNNs.py", line 92, in <module>
    nu=(1e-4, 1e-2),
TypeError: __init__() got an unexpected keyword argument 'inpt_shape'

**Comment by Hananel-Hazan** [comment]
Hi @CHonChou , I am running the same script without any issue. Please make sure you are using the latest version from the GitHub.
