### ISSUE TITLE
Order of MNIST images depends on n_neurons in supervised_mnist.py example?!

### ISSUE THREAD

**Issue by Danielle-Schuman** [BindsNET/bindsnet#398]
While I was trying out different hyper parameter configurations for the supervised_mnist.py example, I noticed a peculiar thing:
When running the example with the same hyper parameters, the order of MNIST example images would always be the same, i.e. when looking at the labels after update_interval images, it would always be the same sequence of numbers. So far nothing weird, when running with seed = 0, i.e. the execution being deterministic.
However, when I change only the number of `neurons n_neurons`, this sequence of labels changes.
E.g. when running with the parameter configuration `--n_clamp 0 --intensity 170 --inh 60 --n_neurons X --n_train 1000 --n_test 0 --time 40 --update_interval 50`
for 

- X = 80 I would get the sequence of labels 3, 7, 6, 2, 7, 1, 9, 0, 5, 7, 5, 1, ...

- X = 100 I would get 0, 4, 1, 8, 6, 4, 6, 4, 6, 7, 0, 7, ...

- X = 120 I would get 9, 1, 7, 9, 7, 8, 0, 9, 0, 3, 4, 9, ...

etc. 
This does not make any sense to me as, in my understanding, `n_neurons` is neither used in loading or preparing the dataset, nor in choosing images from it, nor is it used as a random seed or the like. 
Does anyone have an idea why this could be happening? (And if not: Might this be an issue inherent to PyTorch?) 
I would greatly appreciate an answer :).

Kind regards

P.S. I made sure to use the newest version of BindsNET when trying this out

**Comment by Hananel-Hazan** [comment]
I have a couple of guesses.
1. We may need to set the `numpy` random generator and not only the torch one.
2. Maybe torch random seed and numpy random seed are connected somehow. The `n_neurons` use also by `numpy` random generator to draw the input neurons (line 195)
3. When you set the random seed, the sequence of random numbers is deterministic. That suggests that somewhere else in the script (BindsNET, PyTorch, etc) also draw more (or less) numbers from that random sequence. Therefore the labels sequence changed. 

Is this seems reasonable?

**Comment by Danielle-Schuman** [comment]
Yes, that actually makes a lot of sense. Thank you very much :)
