### ISSUE TITLE
Does Bindsnet admit to craete deep layers SNN?

### ISSUE THREAD

**Issue by jcmharry** [BindsNET/bindsnet#399]
Hi, when I try to create a three or four layers SNN, it always come across the error "The size of tensor a (300) must match the size of tensor b (800) at non-singleton dimension 1". So what is the problem? Thanks.

`source_layer = Input(n=100,traces=True)
target_layer = LIFNodes(n=300,traces=True)
target_layer2 = LIFNodes(n=800,traces=True)
network.add_layer(
    layer=source_layer, name="A"
)
network.add_layer(
    layer=target_layer, name="B"
)
network.add_layer(
    layer=target_layer2, name="C"
)

forward_connection = Connection(
    source=source_layer,
    target=target_layer,
    w=0.05 + 0.1 * torch.randn(source_layer.n, target_layer.n),  # Normal(0.05, 0.01) weights.
    update_rule=PostPre,
    nu=0.01,
)
network.add_connection(
    connection=forward_connection, source="A", target="B"
)

output_connection = Connection(
    source=target_layer,
    target=target_layer2,
    w=0.025 * (torch.eye(target_layer.n) - 1), # Small, inhibitory "competitive" weights.
    update_rule=PostPre,
    nu=0.01,
    )

network.add_connection(
    connection=output_connection, source="B", target="C"
)`

**Comment by SimonInParis** [comment]
Hi.
Last line reads target='0' which is not defined. 'All to all' connection
like Connection() should deal with your architecture nicely. Please provide
more of your architecture code if the problem persists.
Simon Caby

**Comment by Hananel-Hazan** [comment]
@jcmharry with the last change that you made to your post, the code works fine on my end. 
If you have further issues, please make sure that you using the right BindsNET version and post the full code that can replicate the problem.

**Comment by jcmharry** [comment]
Thanks a lot!
