### ISSUE TITLE
have a bug in BindsNET of examples(mnist\SOM_LM-SNNs.py)

### ISSUE THREAD

**Issue by Lizhanying-Sudo** [BindsNET/bindsnet#401]
hi, i had a error in BindsNET of examples(mnist\SOM_LM-SNNs.py), did you have the error?
 my error content(AttributeError: Can't pickle local object 'create_torchvision_dataset_wrapper.<locals>.TorchvisionDatasetWrapper') 
my env is python36 cuda10.2 torch16.0 torchvision0.7.0 binsnet0.2.7
by the way, if i set n_workers=1, the code can work, but cuda is available. i can't find the problem. 
i am looking forward to your reply soon.

**Comment by SimonInParis** [comment]
Hi. So far, BindsNet is only tested with torch 1.5.0
Can you try downgrading torch version and see if the problem is still here?
Did you set cuda usage?
Simon

**Comment by Lizhanying-Sudo** [comment]
hi simon, so lucky to see u again, i am monica in youtube talking the error.
actually, i try your suggestion. but it alway didn't work.

**Comment by Lizhanying-Sudo** [comment]
maybe, because my OS is window7, pytorch recommand os is windows10 or greater, though windows7 is permitted.
if can't find method, i will try to change my OS.

**Comment by SimonInParis** [comment]
You can try to 'pip install torch==1.5.0' to force version. See what happens.

**Comment by Lizhanying-Sudo** [comment]
i can't do it, i received a error.
No matching distribution found for torch==1.5.0

**Comment by Hananel-Hazan** [comment]
Hi @Lizhanying-Sudo, I tend to believe that it is a Windows/PyTorch issue. Since I can't replicate the issue and google search of the error message led me to many posts on  PyTorch forum that with a similar issue, and since each one of the logs in the posts had a windows path.
Try to use WSL2 with GPU on windows, its seems to solve many issues in development

**Comment by Lizhanying-Sudo** [comment]
hai @Hananel-Hazan , i am so excited you reply to me and take a method. thank u very much. you are so nice.
I will try your suggestion.
