### ISSUE TITLE
what are the difference between the example eth_mnist.py and the proposed network by Diehl & Cook 2015.

### ISSUE THREAD

**Issue by jcmharry** [BindsNET/bindsnet#405]
Hi, I have found the example eth_mnist.py is much faster while training the weights in the excitatory layer, howvere, the learning rate keeps same as Diehl & Cook 2015, are there any other factors which lead to a faster training? And the testing accuracy is lower than original paper, so I wonder what the differences between the example eth_mnist.py and the proposed network by Diehl & Cook 2015 are. Thanks.

**Comment by Hananel-Hazan** [comment]
Diehl & Cook script works with Brian simulator that uses a different method to calculate the LIF neuron. Moreover, Brian uses more complex synapses to transmit the spikes between neurons. There are probably more changes than this, but that enough to make some differences between the two platforms. Especially in our case, where we use the current values to calculate the next steps, like in any other dynamic system, small changes can offset you in the long run.  
To increase accuracy, run a parameter search to find the best parameters.
