### ISSUE TITLE
a little bug

### ISSUE THREAD

**Issue by SeniorCtrlPlayer** [BindsNET/bindsnet#410]
https://github.com/BindsNET/bindsnet/blob/70d91607919b1b3f75b048c1c1e7312e4dd70d50/bindsnet/analysis/plotting.py#L383

`ticks` should be `list(range(-1, 10))`

**Comment by Hananel-Hazan** [comment]
Thanks for reporting this, however, I think the problem comes from somewhere else. try the last PR and let me know

**Comment by SeniorCtrlPlayer** [comment]
> Thanks for reporting this, however, I think the problem comes from somewhere else. try the last PR #411 and let me know

`yticklabels` and `ticks` need list with same length, setting `["none"] + list(range(11)` in `yticklabels` is worked too 😸

**Comment by Hananel-Hazan** [comment]
yes, your right. 
Anyhow, glad that is work out.
