### ISSUE TITLE
Indices of plot_spikes function seems to be swapped

### ISSUE THREAD

**Issue by ruteee** [BindsNET/bindsnet#414]
When running the plot_spikes function on the reservoir mnist example, the indices for neuron and time seems to be incorrect. 
That is, neurons are in the domain (0 - 250) which is the time parameter domain. Whereas the time parameter is set from 0 to 784, which is the number of neurons in the input layer, in both the input and output layers plot.

![swapped_indices](https://user-images.githubusercontent.com/13775309/94034298-3b4d4f00-fd98-11ea-9d3b-b731cfafbfe8.png)

In the print above the definition of time is made with index 0 from the shape of the spikes. 

time = (0, spikes[key].shape[0])

And the neurons are made with the index 1, from the shape of the spikes

n_neurons[key] = (0, val.shape[1])

Which produces the following output on plot window:

![old_plot](https://user-images.githubusercontent.com/13775309/94034694-b0208900-fd98-11ea-9f75-391d5aa3d828.png)

If I change the indices, setting 1 to time definition and 0 to neurons definitions, the output seems to make more sense:

![new_plot](https://user-images.githubusercontent.com/13775309/94035020-0392d700-fd99-11ea-9277-9d8cb058bd1c.png)

The code snippet would change to:

![snippet correted](https://user-images.githubusercontent.com/13775309/94035149-2624f000-fd99-11ea-98e4-7525d2c4208a.png)

**Comment by Hananel-Hazan** [comment]
Good catch.
Can you submit a PR with this change?

**Comment by ruteee** [comment]
Yes, for sure.

**Comment by Hananel-Hazan** [comment]
Thanks for your help and submitting the PR #415
