### ISSUE TITLE
Perhaps a useless code line

### ISSUE THREAD

**Issue by SeniorCtrlPlayer** [BindsNET/bindsnet#419]
https://github.com/BindsNET/bindsnet/blob/ff5925dfb03802ed1783fe0f8160e11c81e21a01/bindsnet/network/network.py#L393

After this line, the `current_inputs` is unused in this for loop, but the `current_inputs` will be set `{}` at the beginning of the next for loop.
So, I think it's useless

**Comment by Hananel-Hazan** [comment]
Thanks for bring it up, its seems that you are correct. But I will take a look deeper at the weekend
