### ISSUE TITLE
Possibilities to implement custom gym environment 

### ISSUE THREAD

**Issue by Narinder-1986** [BindsNET/bindsnet#422]
Can we implement custom gym environment, What will be the good practice ? 

Like, do we have to just develop own custom environment and install it ( with pip install -e .) or directly have to work on GymEnvironment and modify it for making own environment?

**Comment by Hananel-Hazan** [comment]
You can use any environment that you wish to use. Just feed the spiking network with the relevant input and activate or modify the STDP strength according to the reward.

**Comment by Narinder-1986** [comment]
Ok Thanks, I will try.
