### ISSUE TITLE
Are there any SNN doing regression task examples?

### ISSUE THREAD

**Issue by Originofamonia** [BindsNET/bindsnet#424]
Hi,

I really appreciate your work in building this SNN development framework. It helps my research work a lot.
Can I ask are there any work related to SNN doing regression tasks? Whether it's some papers or code. I tried to search online, but haven't found any related work.

Thanks!

**Comment by Huizerd** [comment]
You might want to look at SNNs for control (e.g. in a reinforcement learning sense), such as these: https://arxiv.org/abs/2010.09635, https://arxiv.org/abs/2003.03118

**Comment by Hananel-Hazan** [comment]
Thanks @Huizerd.

Here are couple of papers on the subject:
[Backpropagation and the brain](https://www.nature.com/articles/s41583-020-0277-3)
[A Calculus for Brain Computation](https://ccneuro.org/2019/proceedings/0000998.pdf)
[A solution to the learning dilemma for recurrent networks of spiking neurons](https://www.biorxiv.org/content/biorxiv/early/2019/08/19/738385.full.pdf)
