### ISSUE TITLE
The accuracy of the eth_minist.py

### ISSUE THREAD

**Issue by ZulunZhu** [BindsNET/bindsnet#426]
I run the code of eth_minist and found that the accuracy of the test(79%) is far away from the accuracy reported by the paper(95%). I want to know why does it happen?

**Comment by SimonInParis** [comment]
Hi.
You can try to change the number of neurons with the --n_neurons=100 option.
Try a square value, like 900 (30x30) to get a good accuracy.
Optimum results are using 1600 neurons or more I think (6400?).
Simon
