### ISSUE TITLE
Indefinite addition of input spikes

### ISSUE THREAD

**Issue by sidharthanup** [BindsNET/bindsnet#434]
I noticed that at each time step, input spike is added to the current input (See: https://github.com/BindsNET/bindsnet/blob/master/bindsnet/network/network.py#L349). What about the case when there is spike inactivity in certain nodes in the input layer for a number of time steps. In this case, shouldn't we reset the current_input value of those nodes (to 0)?

Apologies if I missed something important.

**Comment by Hananel-Hazan** [comment]
In case the node is from Input [type](class Input(Nodes, AbstractInput):) the node has no residual input from the last iteration. The input node simply transmits the input from the current iteration. 
In case the node is from another type (not Input node), it depends on your use case. In any case, each node process the current input in a different way, some act like capacitors others don't have any memory from the last iteration.

**Comment by sidharthanup** [comment]
Thank you for the response. I'm still a bit confused because in the case of a layer of nodes of class Input, the spike input at each time step seems to be added to the current_input[l] vector (https://github.com/BindsNET/bindsnet/blob/master/bindsnet/network/network.py#L349) and it is this current_input[l] that seems to be propagated forwards (https://github.com/BindsNET/bindsnet/blob/master/bindsnet/network/network.py#L358) and set to the spike value (https://github.com/BindsNET/bindsnet/blob/master/bindsnet/network/nodes.py#L220).

**Comment by Hananel-Hazan** [comment]
Right, Input units is not a neuron, the unit doesn't retain any memory from the last iteration, it only serves as a transmission unit, therefore there is no need to reset the unit after a spike. 
In case input units get an analog signal or spike trains like in the BindsNET examples, the current input transmits the signal via the weights (multiply by the weights) to the neurons in the next layer. 
Inactivity in the input unit means that the Input unit gets zero as input. In this case, the output will be zero as well. 
Inactivity at other units like LIF the leak will decay the current value of the units until it reaches a resting value. 
In case of Inactivity in IF, the last value of the unit will continue indefinitely, or until new input arrives.

**Comment by sidharthanup** [comment]
Thanks again for the explanation! So if I understand correctly, when Network.run() is called then for the Tth time step:

1) current_input[L] are the inputs computed to the units at the layer L (This applies to the layer corresponding to any node classes).
2) input[L][T] are the spike inputs (corresponding to the Tth time step) to the units at the Input layer L. (This applies to the layer corresponding to the Input node class only).

Now if we consider an Input layer L1 with an input spike vector of only zeros, i.e no spiking activity, at time say T1
then since 
```current_input[L1] = current_input[L1] + input[L1][T1]```

and `input[L1][T1]` is a vector of zeros then we get the same current_input[L1] as time T1 - 1 which may be non-zero.

So my confusion stems from the fact that it is this non-zero current_input[L1] vector that seems to be forward propagated (multiplied by weights as you mentioned) to the next layer and yield a non zero PSC, in contrast to getting zero as you mentioned. See: https://github.com/BindsNET/bindsnet/blob/master/bindsnet/network/network.py#L358.

Note: I am only talking about the layers of Input Class.

Sorry if I am missing something trivial and sounding redundant. I'm still in the process of getting comfortable with the code.

**Comment by Hananel-Hazan** [comment]
Please email me and we zoom the issue here
