### ISSUE TITLE
How do you determine the number of input neurons?

### ISSUE THREAD

**Issue by ryunosuke0723** [BindsNET/bindsnet#442]
I want to use something that is not an image for this library.
The input is a [1,64] array and the label is a [1,6] array. How do you calculate the number of input and output neurons?
 Currently, 64 neurons are used for input, but the accuracy is about 40%.

**Comment by Hananel-Hazan** [comment]
Thank you for using BindsNET. 
Like any other neuronal network, spiking neurons are no different. There are no rules or calculations that can give you the optimal size of the network. There are many thumb rules out there, but I'm not aware of something accurate. I suggest using an exploratory search to find the optimal number.
