### ISSUE TITLE
Short Term Synaptic Plasticity

### ISSUE THREAD

**Issue by sidharthanup** [BindsNET/bindsnet#444]
Introduce Short Term Plasticity (STP) - Short Term Facilitation (STF) and Short Term Depression (STD) (http://www.scholarpedia.org/article/Short-term_synaptic_plasticity) as part of the neuron dynamics (Or another model). Both these phenomena model different PSP responses based on the time interval between two presynaptic spikes.

**Comment by Hananel-Hazan** [comment]
Wonderful! thank you for the nice addition #443 to BindsNET

**Comment by ago109** [comment]
> Introduce Short Term Plasticity (STP) - Short Term Facilitation (STF) and Short Term Depression (STD) (http://www.scholarpedia.org/article/Short-term_synaptic_plasticity) as part of the neuron dynamics (Or another model). Both these phenomena model different PSP responses based on the time interval between two presynaptic spikes.

Just a small note of interest to you, @sidharthanup, a different (Python JAX-based) computational neuroscience library **ngc-learn** ( https://github.com/NACLab/ngc-learn ) implements short-term plasticity and can simulate STF and STD (as is shown in one of its tutorials). Just thought this might of interest as efficient implementations of STP are not always easy to come by but ngc-learn offers one of them for nice experimentation =)

**Comment by Hananel-Hazan** [comment]
Thank you for advertising your package. This additional code has already merged back at 2020. 
This ticket will be close.
