### ISSUE TITLE
Time series example

### ISSUE THREAD

**Issue by seyfullah** [BindsNET/bindsnet#445]
Hello,

Is there a way to implement CNN for time series data in Bindsnet?
I see MNIST and GYM datasets.
But how can I implement a CNN for time series data in Bindsnet?

Regards.

**Comment by SimonInParis** [comment]
Hi.
Being temporal by nature, SNN can be trained on time series.
You have to choose the best function to convert your data into temporal
spikes, and feed your network with it.
Many spike encoding functions have been proposed in the literature (for
finance, movement/speech analysis...).
Agreed, it would be nice to have a working example.
S
