### ISSUE TITLE
Plot Update Problem

### ISSUE THREAD

**Issue by BurcuKartal** [BindsNET/bindsnet#448]
Hi everyone. I'm working with code eth_mnist.py but I have a problem. I am new in this field and maybe this is a very simple problem. I run code eth_mnist.py and the code runs and ends with no errors. However, none of the plots are updated. All plots appear once when the train first starts and most of them are empty. They are never updated or changed afterwards. I cannot use GPU and CUDA, the code works with the CPU, maybe the problem is caused by this. I will add here my plots and the results that I want to get for a better explanation. How can I solve this problem?

Results that I want:
https://images.app.goo.gl/VCCTkR4tsV5aS5bB9

My Plots:
![image](https://user-images.githubusercontent.com/37499788/103883108-ceaf5380-50ed-11eb-91f3-4ec766e3185f.png)

**Comment by Hananel-Hazan** [comment]
Already open on https://gitter.im/bindsnet_/community
