### ISSUE TITLE
Right way to implement sparse connectivity with learning rules.

### ISSUE THREAD

**Issue by AaronSpieler** [BindsNET/bindsnet#454]
Hello,

whats the proper way in this library to have sparse connectivity with learning rules activated?
(e.g. SparseConnection doesn't support PrePost)

Best,
Aaron

**Comment by SimonInParis** [comment]
Hi Aaron,

You can use a classic fully connected `Connection()` and specify a `mask` that clamps all selected weights to 0.
The number of connections will be n x m, but depending on your input, you can speed things up by splitting the input into multiple layers, if the total # of connections grows too big.
When running on a GPU, the high level of parallelization will help achieving fast computation on these large matrices.

You can also have a look at `LocalConnection()` too, if it suits your needs.

Simon

**Comment by Hananel-Hazan** [comment]
Thanks @SimonInParis !

Hi @AaronSpieler, there are plans to support sparse connectivity, but currently BindsNET only have basic support (mainly place holders inn the code) for sparse topology. We are ready to support it and waiting to PyTorch to write the necessary operations.

**Comment by ZackWave** [comment]
> 嗨亚伦，
> 
> 您可以使用经典的全连接并指定将所有选定权重夹紧为 0。连接数将为 n x m，但根据您的输入，如果连接总数 # 增长太大，您可以通过将输入拆分为多个层来加快速度。在 GPU 上运行时，高水平的并行化将有助于在这些大型矩阵上实现快速计算。`Connection()``mask`
> 
> 如果适合您的需求，您也可以看看。`LocalConnection()`
> 
> 西蒙

If the post-pre learning rule is applied, it won't work. Are there any other solutions?

**Comment by Hananel-Hazan** [comment]
@ZackWave Not sure what do you mean? what wouldn't work? What code do you use? Is this connect to the issue here about sparse connectivity?
