### ISSUE TITLE
AttributeError: The eth_mnist.py example can't runing on GPU

### ISSUE THREAD

**Issue by envysir** [BindsNET/bindsnet#459]
Hello, Bindsnet
I've tried runing the eth_mnist example in version 0.2.8, the code runing on CPU, it's OK.
But I want to running on GPU, I set this code in Line 47  `parser.set_defaults(plot=True, gpu=True)`

The Traceback are as follows:

        Running on Device =  cuda
                
        Begin training.
        
        Progress: 0 / 1 (0.0000 seconds)
          0%|          | 0/60000 [00:00<?, ?it/s]
        Traceback (most recent call last):
          File "D:/Code/bindsnet-master/examples/mnist/eth_mnist.py", line 175, in <module>
            for step, batch in enumerate(tqdm(dataloader)):
          File "D:\Software\ANACONDA\Anaconda\envs\bindsnet\lib\site-packages\tqdm\std.py", line 1166, in __iter__
            for obj in iterable:
          File "D:\Software\ANACONDA\Anaconda\envs\bindsnet\lib\site-packages\torch\utils\data\dataloader.py", line 352, in __iter__
            return self._get_iterator()
          File "D:\Software\ANACONDA\Anaconda\envs\bindsnet\lib\site-packages\torch\utils\data\dataloader.py", line 294, in _get_iterator
            return _MultiProcessingDataLoaderIter(self)
          File "D:\Software\ANACONDA\Anaconda\envs\bindsnet\lib\site-packages\torch\utils\data\dataloader.py", line 801, in __init__
            w.start()
          File "D:\Software\ANACONDA\Anaconda\envs\bindsnet\lib\multiprocessing\process.py", line 105, in start
            self._popen = self._Popen(self)
          File "D:\Software\ANACONDA\Anaconda\envs\bindsnet\lib\multiprocessing\context.py", line 223, in _Popen
            return _default_context.get_context().Process._Popen(process_obj)
          File "D:\Software\ANACONDA\Anaconda\envs\bindsnet\lib\multiprocessing\context.py", line 322, in _Popen
            return Popen(process_obj)
          File "D:\Software\ANACONDA\Anaconda\envs\bindsnet\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
            reduction.dump(process_obj, to_child)
          File "D:\Software\ANACONDA\Anaconda\envs\bindsnet\lib\multiprocessing\reduction.py", line 60, in dump
            ForkingPickler(file, protocol).dump(obj)
        AttributeError: Can't pickle local object 'create_torchvision_dataset_wrapper.<locals>.TorchvisionDatasetWrapper'

This is the output of `pip list`

          alabaster                     0.7.12
          appdirs                       1.4.4
          argon2-cffi                   20.1.0
          async-generator               1.10
          atomicwrites                  1.4.0
          attrs                         20.3.0
          Babel                         2.9.0
          backcall                      0.2.0
          BindsNET                      0.2.8               d:\code\bindsnet-master
          bleach                        3.2.2
          certifi                       2020.12.5
          cffi                          1.14.4
          cfgv                          3.2.0
          chardet                       4.0.0
          cloudpickle                   1.6.0
          colorama                      0.4.4
          cycler                        0.10.0
          Cython                        0.29.21
          dataclasses                   0.7
          decorator                     4.4.2
          defusedxml                    0.6.0
          distlib                       0.3.1
          distro                        1.5.0
          docutils                      0.16
          eagerpy                       0.29.0
          entrypoints                   0.3
          filelock                      3.0.12
          foolbox                       3.2.1
          future                        0.18.2
          gitdb                         4.0.5
          GitPython                     3.1.12
          gym                           0.18.0
          identify                      1.5.13
          idna                          2.10
          imageio                       2.9.0
          imagesize                     1.2.0
          importlib-metadata            3.4.0
          importlib-resources           5.1.0
          iniconfig                     1.1.1
          ipykernel                     5.3.4
          ipython                       7.16.1
          ipython-genutils              0.2.0
          ipywidgets                    7.6.3
          jedi                          0.18.0
          Jinja2                        2.11.2
          joblib                        1.0.0
          jsonschema                    3.2.0
          jupyter                       1.0.0
          jupyter-client                6.1.7
          jupyter-console               6.2.0
          jupyter-core                  4.7.0
          jupyterlab-pygments           0.1.2
          jupyterlab-widgets            1.0.0
          kiwisolver                    1.3.1
          MarkupSafe                    1.1.1
          matplotlib                    3.3.3
          mistune                       0.8.4
          mkl-fft                       1.2.0
          mkl-random                    1.1.1
          mkl-service                   2.3.0
          nbclient                      0.5.1
          nbconvert                     6.0.7
          nbformat                      5.1.2
          nest-asyncio                  1.4.3
          networkx                      2.5
          nodeenv                       1.5.0
          notebook                      6.2.0
          numpy                         1.19.5
          olefile                       0.46
          opencv-python                 4.5.1.48
          packaging                     20.8
          pandas                        1.1.5
          pandocfilters                 1.4.3
          parso                         0.8.1
          pickleshare                   0.7.5
          Pillow                        7.2.0
          pip                           20.3.3
          pluggy                        0.13.1
          pre-commit                    2.9.3
          prometheus-client             0.9.0
          prompt-toolkit                3.0.8
          protobuf                      3.14.0
          py                            1.10.0
          pycparser                     2.20
          pyglet                        1.5.0
          Pygments                      2.7.4
          pyparsing                     2.4.7
          pyrsistent                    0.17.3
          pytest                        6.2.1
          python-dateutil               2.8.1
          pytz                          2020.5
          PyWavelets                    1.1.1
          pywin32                       227
          pywinpty                      0.5.7
          PyYAML                        5.4.1
          pyzmq                         20.0.0
          qtconsole                     4.7.7
          QtPy                          1.9.0
          requests                      2.25.1
          scikit-build                  0.11.1
          scikit-image                  0.17.2
          scikit-learn                  0.24.1
          scipy                         1.5.4
          Send2Trash                    1.5.0
          setuptools                    51.3.3.post20210118
          six                           1.15.0
          smmap                         3.0.5
          snowballstemmer               2.1.0
          Sphinx                        3.4.3
          sphinx-rtd-theme              0.5.1
          sphinxcontrib-applehelp       1.0.2
          sphinxcontrib-devhelp         1.0.2
          sphinxcontrib-htmlhelp        1.0.3
          sphinxcontrib-jsmath          1.0.1
          sphinxcontrib-qthelp          1.0.3
          sphinxcontrib-serializinghtml 1.1.4
          tensorboardX                  2.1
          terminado                     0.9.2
          testpath                      0.4.4
          threadpoolctl                 2.1.0
          tifffile                      2020.9.3
          toml                          0.10.2
          torch                         1.7.1
          torchaudio                    0.7.2
          torchvision                   0.8.2
          tornado                       6.1
          tqdm                          4.56.0
          traitlets                     4.3.3
          typing-extensions             3.7.4.3
          urllib3                       1.26.2
          virtualenv                    20.4.0
          wcwidth                       0.2.5
          webencodings                  0.5.1
          wheel                         0.36.2
          widgetsnbextension            3.5.1
          wincertstore                  0.2
          zipp                          3.4.0

I think the cude is work in pytorch

        import torch
        torch.cuda.current_device()
        Out[3]: 0
        torch.cuda.device_count()
        Out[5]: 1
        torch.cuda.device(0)
        Out[6]: <torch.cuda.device at 0x1eb84955b38>
        torch.cuda.get_device_name(0)
        Out[7]: 'GeForce RTX 2060'
        torch.cuda.is_available()
        Out[8]: True

Is a certain part of the program not configured correctly? Sorry for long issue, Hope to get an answer, Thanks a lot!

Jayden

**Comment by Hananel-Hazan** [comment]
Hi @envysir , thanks for posting this. 
I suspect this issue is a result of the semi-supported part between windows and PyTorch/Cuda. The code runs fine on Linux and WSL2 with GPU (although WSL2 have slow GPU performance, but it works without an issue).

If you run a google on : ```PyTorch dataloader AttributeError: Can't pickle local object 'create_torchvision_dataset_wrapper.<locals>.TorchvisionDatasetWrapper'``` I believe you can come to the same conclusion, that there is problem with PyTorch on windows with lambda calculation 

If you want to try to play with the code, try not to use `lambda` calculation in line 120. I think this may resolve the issue.
