### ISSUE TITLE
"Matrices expected, got 3D tensor" when working with SparseConnections

### ISSUE THREAD

**Issue by Afstkla** [BindsNET/bindsnet#460]
Hi there,

I'm trying to replicate [LSNN](https://github.com/IGITUGraz/LSNN-official) (see figure below) in BindsNET, but I'm running into some problems with SparseConnections.
![IMG_9336](https://user-images.githubusercontent.com/9075380/108858740-c7d09780-75ec-11eb-8abe-acd369222beb.png)

The code below shows a small example of what I'm experiencing
```python
import torch
from bindsnet.network import Network
from bindsnet.network.nodes import Input, LIFNodes
from bindsnet.network.topology import SparseConnection
from torchneuromorphic.nmnist.nmnist_dataloaders import create_datasets

batch_size = 4
time = 300

# Build network.
network = Network()
x_layer = Input(32 * 32 * 2)
e_layer = LIFNodes(10)

network.add_layer(
    layer=x_layer,
    name='X'
)
network.add_layer(
    layer=e_layer,
    name='E'
)


x_e_conn = SparseConnection(
    source=x_layer,
    target=e_layer,
    sparsity=0.15
)

network.add_connection(
    connection=x_e_conn,
    source="X",
    target="E"
)

train_dataset, test_dataset = create_datasets()
n_test = test_dataset.n

network.train(mode=False)

test_dataloader = torch.utils.data.DataLoader(
    test_dataset, batch_size=batch_size, shuffle=True
)

for step, batch in enumerate(test_dataloader):
    if step > n_test:
        break
    # Get next input sample, shape [time, batch_size, x * y * channels], with x = 32, y = 32, channels = 2 (one
    # positive, one negative).
    inputs = {"X": batch[0].permute(1, 0, 2, 3, 4).view(time, batch_size, 1, 1, -1).squeeze()}

    # Run the network on the input.
    network.run(inputs=inputs, time=time, input_time_dim=1)
```

This gives me the following error:
```python
Traceback (most recent call last):
  File "/Users/me/PycharmProjects/BindsNETLayers/min_example.py", line 54, in <module>
    network.run(inputs=inputs, time=time, input_time_dim=1)
  File "/Users/me/PycharmProjects/BindsNETLayers/venv/lib/python3.8/site-packages/bindsnet/network/network.py", line 354, in run
    current_inputs.update(self._get_inputs())
  File "/Users/me/PycharmProjects/BindsNETLayers/venv/lib/python3.8/site-packages/bindsnet/network/network.py", line 245, in _get_inputs
    inputs[c[1]] += self.connections[c].compute(source.s)
  File "/Users/me/PycharmProjects/BindsNETLayers/venv/lib/python3.8/site-packages/bindsnet/network/topology.py", line 822, in compute
    return torch.mm(self.w, s.unsqueeze(-1).float()).squeeze(-1)
RuntimeError: addmm: matrices expected, got 3D tensor
```

It seems that the dimensions of `s` and `self.w` are not matching up. When I try to play around with the dimensions I can fix the unexpected 3D tensor, but I'm greeted with another error: `RuntimeError: sparse tensors do not have strides`. `self.w` is a sparse tensor, so it doesn't seem to be possible to use `torch.mm` on that tensor at all?

Please tell me if I'm missing something.

Best

**Comment by Afstkla** [comment]
Just a quick addition, originally I had the input be:
```python
x_layer = Input(shape=[32, 32, 2])
```

and set the `inputs` to:
```python
inputs = {"X": batch[0].permute(1, 0, 2, 3, 4)}
```

But that resulted in a very similar error to the first error, only with `RuntimeError: addmm: matrices expected, got 4D tensor` except `3D tensor`

**Comment by Afstkla** [comment]
The only output that doesn't crash I've managed to achieve was by changing the `compute` function from
```python
return torch.mm(self.w, s.unsqueeze(-1).float()).squeeze(-1)
```

to

```python
return torch.mm(self.w.transpose(1, 0), s.permute(1, 0).float())
```

But I'm not sure if that gives the correct output, or if I'm on the entirely wrong path.

**Comment by Hananel-Hazan** [comment]
Hi @Afstkla, 
The network you are trying to implement looks very interesting.

Sadly, sparse matrices is still in beta stage on [PyTorch](https://pytorch.org/docs/stable/sparse.html). On BindsNET side we still missing some math operation to fully take advantage of this nifty feature. Try to use a regular weights, I hope that will solve the problem for now. 
When PyTorch support all the math operations that BindsNET need, we will add it too.
