### ISSUE TITLE
Couple of errors in eth_mnist.py

### ISSUE THREAD

**Issue by GutiPerez** [BindsNET/bindsnet#479]
Hi, I found the following errors in the file _eth_mnist.py_:

1. The initialization of the variable _labels_, on line 171, should be inside the _for_ loop in line 172. Otherwise, when you use more than one epoch, you will carry an additional element in _labels_ from the previous epoch, and eventually, an error would raise in lines 209 and 214, as _label\_tensor_ and _all_activity\_pred_ or _proportion\_pred_ tensors will have different sizes.

2.  In the testing part, there is an error regarding the mean calculation on lines 352 and 353. The problem is that you are dividing by _n\_test_, but because of the condition of the _if_, in line 315, is ">", instead of doing n\_test evaluations, you are doing n\_test+1, so the mean calculation is not correct. Given that you are using directly _n\_test_, it would suggest changing the ">" by an ">=". Another option would be to divide by n\_test+1, meaning that n\_test starts from 0, which makes less sense for me.

**Comment by SimonInParis** [comment]
Hi. Good catch. Thanks!

The first issue has been fixed in the batch version of eth (_batch_eth_mnist.py_), but needs a fix in _eth_mnist.py_.
The second point needs to be fixed too, as some people may want to test on a smaller test subset.
Thanks!

**Comment by Hananel-Hazan** [comment]
Thanks @GutiPerez for notice this and let us know. 
@SimonInParis just submit the fix #482
