### ISSUE TITLE
How can i find 'DatasetEnvironment' class?

### ISSUE THREAD

**Issue by eungyeol1** [BindsNET/bindsnet#480]
![noname01](https://user-images.githubusercontent.com/83384631/116497805-2cf18380-a8e3-11eb-9a77-64bc2b8ceffe.png)
I want to run this code, but i can't find 'DatasetEnvironment' class. Does it exist only in the previous version?

**Comment by Hananel-Hazan** [comment]
Thanks for using BindsNET, the class that you trying to use is deprecated. Currently all the datasets are under:
bindsnet/bindsnet/datasets/

Please use the examples to learn how BindsNET import the MNIST dataset, for example 
https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/eth_mnist.py
