### ISSUE TITLE
How to make the LIFNodes to be non-spiking (non-firing)?

### ISSUE THREAD

**Issue by AptX395** [BindsNET/bindsnet#481]
For example, another SNN simulation library called SpikingJelly has provided a way to make their LIFNode to be non-spiking in their documents, like this:

> Here, we apply a new method to make SNN output floating numbers. We set the firing threshold of a neuron to be infinity, which won’t fire at all, and we adopt the final membrane potential to represent Q function. It is convenient to implement such neurons in the SpikingJelly framework: just inherit everything from LIF neuron neuron.LIFNode and rewrite its forward function.

```python
class NonSpikingLIFNode(neuron.LIFNode):
    def forward(self, dv: torch.Tensor):
        self.neuronal_charge(dv)
        # self.neuronal_fire()
        # self.neuronal_reset()
        return self.v
```

And now I need to use BindsNET to do the same thing. How could I make the LIFNodes to be non-spiking?
Thank you so much!

**Comment by SimonInParis** [comment]
Hi.
Are we talking about LIF neurons that fire internally and provide their membrane potential instead of their actual spike state to the subsequent layers?

**Comment by AptX395** [comment]
> Hi.
> Are we talking about LIF neurons that fire internally and provide their membrane potential instead of their actual spike state to the subsequent layers?

Yes, that's right. Do you know how to do that?

**Comment by SimonInParis** [comment]
It seems we can do the same here in BindsNet. You can overload the forward, and add **self.s = self.v** to it at the end, if it is what you need, so the network will pass it to the next layer.

`class NonSpikingNeuron(LIFNodes):
    def forward(self, x: torch.Tensor) -> None:

        # Decay voltages.
        self.v = self.decay * (self.v - self.rest) + self.rest

        # Integrate inputs.
        x.masked_fill_(self.refrac_count > 0, 0.0)

        # Decrement refractory counters.
        self.refrac_count -= self.dt

        self.v += x  # interlaced

        # Check for spiking neurons.
        self.s = self.v >= self.thresh

        # Refractoriness and voltage reset.
        self.refrac_count.masked_fill_(self.s, self.refrac)
        self.v.masked_fill_(self.s, self.reset)

        # Voltage clipping to lower bound.
        if self.lbound is not None:
            self.v.masked_fill_(self.v < self.lbound, self.lbound)

        super().forward(x)

        self.s = self.v`

**Comment by AptX395** [comment]
> It seems we can do the same here in BindsNet. You can overload the forward, and add **self.s = self.v** to it at the end, if it is what you need, so the network will pass it to the next layer.
> 
> `class NonSpikingNeuron(LIFNodes):
> def forward(self, x: torch.Tensor) -> None:
> 
> ```
>     # Decay voltages.
>     self.v = self.decay * (self.v - self.rest) + self.rest
> 
>     # Integrate inputs.
>     x.masked_fill_(self.refrac_count > 0, 0.0)
> 
>     # Decrement refractory counters.
>     self.refrac_count -= self.dt
> 
>     self.v += x  # interlaced
> 
>     # Check for spiking neurons.
>     self.s = self.v >= self.thresh
> 
>     # Refractoriness and voltage reset.
>     self.refrac_count.masked_fill_(self.s, self.refrac)
>     self.v.masked_fill_(self.s, self.reset)
> 
>     # Voltage clipping to lower bound.
>     if self.lbound is not None:
>         self.v.masked_fill_(self.v < self.lbound, self.lbound)
> 
>     super().forward(x)
> 
>     self.s = self.v`
> ```

Thanks for your help!
