### ISSUE TITLE
An error occurred while updating the network with MSTDP learning rule

### ISSUE THREAD

**Issue by AptX395** [BindsNET/bindsnet#488]
I submitted an issue #487 that explained an error I had encountered.

After investigation, I think it is not because the network parameters were set incorrectly. I replied the [specific disgussion](https://github.com/BindsNET/bindsnet/issues/487#issuecomment-841592109) in #487.

I think this problem may have occurred in the update phase of the network rather than in the forward propagation phase of the network.

My code logic is to separate forward propagation from network updates. That is, I set `self._net.train(mode = False)` before calling `self._net.run()` as follows:

```python
self._net.train(mode = False)
spike = self._encoder(x)    # PoissonEncoder
input = {"input": spike}
self._net.run(input, self._time, one_step = True)
```

to make the network behave like:

```python
with torch.no_grad():
    model.forward(x)
```

in PyTorch.

---

My code works fine for forward propagation without any errors. But when I update network parameters as follows:

```python
self._net.train(mode = True)

for connection in self._net.connections:
    self._net.connections[connection].update(reward = reward)
```

I get the error mentioned in #487.

The most critical error message is:

```python
  File "/usr/local/anaconda3/envs/snn_rl/lib/python3.7/site-packages/bindsnet/learning/learning.py", line 669, in _conv2d_connection_update
    self.eligibility = self.eligibility.view(self.connection.w.size())
RuntimeError: shape '[32, 4, 8, 8]' is invalid for input of size 262144
```

What is the cause of this error?

I really appreciate your help!

**Comment by Hananel-Hazan** [comment]
Can you elaborate more about the way this code been use? at #487 the error code start with loading pickle file. 
`model_path = os.path.join(MODEL_DIR, f"{args.model}_{args.env_id}_{time_str}.pkl"))`

If that so, can you please try to run the code without pickling the network?

**Comment by AptX395** [comment]
> Thank you for investigating the error, indeed this is a strange error.
> 
> Can you elaborate more about the way this code been use? at #487 the error code start with loading pickle file.
> `model_path = os.path.join(MODEL_DIR, f"{args.model}_{args.env_id}_{time_str}.pkl"))`
> 
> If that so, can you please try to run the code without pickling the network?
> 
> Update:
> I run the code under your profile https://github.com/AptX395/SNN_RL and it seems running, or at least the TensorBoeard seems updating. I didnt got the error above. Can you please provide a code that I can replicate the error.

Thank you for trying to run my code.

I run my code by calling `agent.learn()`, and `model_path = os.path.join(MODEL_DIR, f"{args.model}_{args.env_id}_{time_str}.pkl"))` is an arguments to `agent.learn()`.

I'm not sure if you are running DSQN_RSTDP correctly. `python run.py --model=DSQN_RSTDP --device=cpu` is the command I used.

By the way, I also encountered another problem, when I was using the GPU, the program didn't work properly. I repeatedly cheched and tried, and found that it only works properly using the CPU. That's why I use `--device=cpu`.

The environment I'm using is:

**Comment by SimonInParis** [comment]
Hi.
Just ran your code. Still investigating.

It seems we missed a call to the batch reduction() function - which you can select BTW - default function is torch.mean(). I'm still investigating on that.

So I changed your batch size to 1.

It then worked much longer, but still leads to another dimension mismatch later on when applying MSTDP to the all to all Connection, probably due to a missing 'a_plus' argument in your call to the MSTDP?

**Comment by SimonInParis** [comment]
The last bug has been fixed, it's about neuron layers shapes flattening, in the special case of MSTDP on layers with different # of dims.

One open question remains: in the case of simultaneous multiple samples (batch size > 1):
How should MSTDP behave? Should it average/sum all incoming/outgoing spikes and compute synapses's eligibility based on that? Or simply reject batches?

**Comment by AptX395** [comment]
> The last bug has been fixed, it's about neuron layers shapes flattening, in the special case of MSTDP on layers with different # of dims.
> 
> One open question remains: in the case of simultaneous multiple samples (batch size > 1):
> How should MSTDP behave? Should it average/sum all incoming/outgoing spikes and compute synapses's eligibility based on that? Or simply reject batches?

Thank you very much for your investigation! Looking forward to your progress!

**Comment by SimonInParis** [comment]
Thanks. You can update to the latest bindsnet now. Should be fixed. Remember to use a batch of 1 for now.
