### ISSUE TITLE
GymEnvironment.render() not passing additional keyword arguments to the gym env

### ISSUE THREAD

**Issue by camilodoa** [BindsNET/bindsnet#493]
Not sure if this was intentional, but in GymEnvironment's render function there isn't the option of passing kwargs to the OpenAI gym render function, thus limiting the GymEnvironment's functionality:

``` 
def render(self) -> None:
        # language=rst
        """
        Wrapper around the OpenAI ``gym`` environment ``render()`` function.
        """
        self.env.render()
```

I ran into this issue when I wanted to call `render(mode="rgb_array")`.

**Comment by Hananel-Hazan** [comment]
Interesting idea, I can see how this can help, but it also have the potential to destabilize BindsNET gym wrapper. 
Anyhow, make a PR and I will update the repo.

**Comment by camilodoa** [comment]
Thank you! I'm not sure what side effects it could have in the GymEnvironment wrapper class, but it would be useful to have. 😄

**Comment by Hananel-Hazan** [comment]
Closing this for now...
