### ISSUE TITLE
Question: Error when use gpu, tensors not on the same devie.

### ISSUE THREAD

**Issue by isMengxiao** [BindsNET/bindsnet#510]
I used 'torch.set_default_tensor_type("torch.cuda.FloatTensor") but it told me tensors run on both cuda:0 and cpu, not on the same device. I want to run the benchmark.py

`  File "D:/workplace/Benchmark/Test/Bindsnet_MNIST_Test.py", line 14, in <module>
    network.add_layer(layer1, name='l1')

  File "D:\software\Anaconda\envs\torchGPU\lib\site-packages\bindsnet\network\network.py", line 130, in add_layer
    layer.set_batch_size(self.batch_size)

  File "D:\software\Anaconda\envs\torchGPU\lib\site-packages\bindsnet\network\nodes.py", line 554, in set_batch_size
    self.v = self.rest * torch.ones(batch_size, *self.shape, device=self.v.device)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!`

And then I find that you use` self.register_buffer("s", torch.ByteTensor())  # Spike occurrences.` in your codes and this may set the device of "s" to 'cpu' instead of 'cuda:0'.

Is this a bug? or just I don't know how to use it?

**Comment by Hananel-Hazan** [comment]
Hi @isMengxiao,

I am not sure what file are you trying to run. 
From the error you got, its seems that your network is set incorrectly on your device. In addition to `torch.set_default_tensor_type`, use the `.to(device)` command on the network object to place your network on the desired device.
