### ISSUE TITLE
one to one connection 

### ISSUE THREAD

**Issue by mandalbiswadip** [BindsNET/bindsnet#519]
I have multiple layers in my SNN. I want some of them to be one to one rather than fully connected. `Connection` only seems to support fully connected layers. 

Are there any way around to this?

**Comment by Hananel-Hazan** [comment]
You are correct, weights are complete matrix. One can think on clever architectural tricks that can connect smaller network together, but that can work only in small number of cases. Currently BindsNET dont have a way to connect layer beside fully connected matrix. 

If you have an idea for a solution, I am all ears.
