### ISSUE TITLE
Self-made image data set

### ISSUE THREAD

**Issue by guzh970630** [BindsNET/bindsnet#521]
hi~，I would like to ask how to use a self-made image data set. What does the code look like?

**Comment by SimonInParis** [comment]
Hi. You can provide your own dataset and convert it - using Poisson spikes or some other spike conversion.
Let dataset_x be your dataset containing 1000 samples, and "Input" be the name of your input layer, then:

```
for step in range(1000):
  x = binndsnet.encoding.poisson(dataset_x[step], time=max_runtime, dt=1.0)
  model.run(inputs={"Input": x}, time=max_runtime)
```
