### ISSUE TITLE
How to input numpy array into spike neural network

### ISSUE THREAD

**Issue by guzh970630** [BindsNET/bindsnet#523]
![image](https://user-images.githubusercontent.com/68584116/137244711-275413c7-e246-493d-9f4c-9a11f14cf6e3.png)
hi，I would like to ask how to input the numpy array I built into the spike neural network. What is the specific code?

**Comment by Hananel-Hazan** [comment]
The input shape need to be Time X number of neurons (and shape) of the input layer. 
Please see [tutorial](https://bindsnet-docs.readthedocs.io/guide/guide_part_i.html) and the [batch_eth_mnist.py](https://github.com/BindsNET/bindsnet/blob/master/examples/mnist/batch_eth_mnist.py)
