### ISSUE TITLE
Euler approximation in Izhikevich nodes is incorrect

### ISSUE THREAD

**Issue by peschn** [BindsNET/bindsnet#533]
BindsNet version 0.3.0

Hi,

I think there is a mistake in the calculation of the membrane potential update in the Izhikevich neuron. As I understand, it is intended to approximate the differential equation with the improved euler method:

v_(k+1) = v_k + h * f(t_(k + 0.5 * h), v_(k+0.5)) with
v_(k+0.5) = v_k + 0.5 * h * f(t_k, v_k)

The code below (taken from the Izihkevich neuron) doesn't implement the above mentioned procedure and produces an incorrect approximation:

```
self.v += self.dt * 0.5 * (0.04 * self.v ** 2 + 5 * self.v + 140 - self.u + x)
self.v += self.dt * 0.5 * (0.04 * self.v ** 2 + 5 * self.v + 140 - self.u + x)
```

It should be:

```
v_half = self.v + self.dt * 0.5 * (0.04 * self.v ** 2 + 5 * self.v + 140 - self.u + x)
self.v += self.dt * (0.04 * v_half ** 2 + 5 * v_half + 140 - self.u + x) 
```
The problem in the original equations is that the second equation does self.v += ... in which the self.v is not v_k anymore but v_(k+0.5) and the step size is not adjusted to the full step size which leads to the aforementioned error.

Sorry if I misunderstood the equations and what I am writing is wrong.

Best,

P

**Comment by Hananel-Hazan** [comment]
Hi, 

Thank you for bringing this up, you are correct, the two ways of the equation have different results. But looking on the original [code](https://www.izhikevich.org/publications/net.m) at Izhikevich website, the Matlab code have the lines:
` v=v+0.5*(0.04*v.^2+5*v+140-u+I); % step 0.5 ms`
`v=v+0.5*(0.04*v.^2+5*v+140-u+I); % for numerical`
