### ISSUE TITLE
Relation to https://github.com/BINDS-LAB-UMASS/bindsnet

### ISSUE THREAD

**Issue by Tobias-Fischer** [BindsNET/bindsnet#560]
Hi there,

I would like to package BindsNet on conda-forge (see https://github.com/conda-forge/staged-recipes/pull/19428). Conda-forge is "A community-led collection of recipes, build infrastructure and distributions for the conda package manager".

We are wondering what the relationship between this GitHub repo, which is actively maintained and has recent releases, and that of https://github.com/BINDS-LAB-UMASS/bindsnet is (which seems to be the source of the last release of BindsNet on PyPi). Is this repo the official continuation of BindsNet? Are the same people involved? Is there any chance to update BindsNet on PyPi with the latest release here?

Many thanks,
Tobias

**Comment by beenje** [comment]
Note that maintainers could create an [issue in PyPI](https://github.com/pypa/pypi-support/issues) to [request a name transfer](https://peps.python.org/pep-0541/#how-to-request-a-name-transfer). It sounds like this falls under the maintenance of an abandoned project: https://peps.python.org/pep-0541/#continued-maintenance-of-an-abandoned-project

That would make the situation clear.

**Comment by Hananel-Hazan** [comment]
Thank you for your suggestion, I will look into it. 

I will close the issue until I have more updates.
