### ISSUE TITLE
Continuous printing of torch.Size when using Conv2D

### ISSUE THREAD

**Issue by henriquejsb** [BindsNET/bindsnet#565]
Hello,
I was trying to use some Conv2D connections but everytime I  try to train a network my terminal gets flooded with things like these:
![image](https://user-images.githubusercontent.com/33788477/180038339-d2657dcd-5249-4641-a42b-3e291d8fdf1f.png)

I tried to simply run your example  examples/mnist/conv_mnist.py  and the same happens.
Any ideas on how to stop this? 
Thank you!

**Comment by Hananel-Hazan** [comment]
Thank you for reporting this, I removed the debugging print statements from the connection object and pushing the fix.
