### ISSUE TITLE
class LocalConnection have some problems when batch_size bigger than 1

### ISSUE THREAD

**Issue by wangjingtao17** [BindsNET/bindsnet#567]
Class LocalConnection have some problems when batch_size bigger than 1,.
Function 'compute' returns a_post.view(*self.target.shape), without considering batch_size

**Comment by Hananel-Hazan** [comment]
Thanks for reporting this issue. Can you provide a code to reproduce the issue?

**Comment by Hananel-Hazan** [comment]
I'm not able to replicate the problem you encountered. I will open this ticket when I will be able to reproduce the problem.
