### ISSUE TITLE
.pt Archives don't generate after project running

### ISSUE THREAD

**Issue by Josep777** [BindsNET/bindsnet#571]
Hi i'm running the following code that can be found here : https://github.com/GutiPerez/bachelor_thesis_uc3m/blob/master/mnist_network/mnist_snn.py 
and i'm using my own raw archives. I've generated the ubyte and the .gz archives with MNIST format 56x28 pixels images. 

First with the raw folder empty I ran the code with download = True, when the download of the training_dataset and the test_dataset is completed the MNIST 28x28 pixel archives appeared and the network runs using them. Then when it's over, I delete these files and paste my 56x28 archives in the raw folder and ran the code again with download = False (and obviously changing the dimensions of the input to fit the 56 height)

here in line 157 : 
train_dataset = MNIST(
    # The encoding applied to the input data.
    PoissonEncoder(time=time, dt=dt),
    None,
    # Folder where the dataset files are stored.
    root="./data",
    # Wheter to download the dataset (the download page usually fails, so using a local copy is recommended).
    download=True, #False after first download <-------------------------------------
    # Wheter to use train or test files.
    train=True,
    # The transformation applied to the encoded input data.
    transform=transforms.Compose(
        [transforms.ToTensor(), transforms.Lambda(lambda x: x * intensity)]
    ),
)

But the .pt archives do not appear in the processed folder which keeps being empty after the running is complete. Why am i not receiving the .pt? Why are they not being generated in the processed folder? 

Thanks in advance

**Comment by Hananel-Hazan** [comment]
Thank you for using BindsNET. 
Does the pt files appear when using the standard MNIST dataset?

**Comment by Josep777** [comment]
I suppose you are referring to network.pt, proportions.pt and assignments.pt, those are generated with no issue. I meant the processed files that should appear in the "processed" folder inside TorchDatasetWrapper. Those files would be train.pt and test.pt and I think those are generated by Bindsnet after running am I wrong?

Thanks in advance

**Comment by Hananel-Hazan** [comment]
I didnt run the above code, but when I run the MNIST example from BindsNET the MNIST dataset appear saved in this way:
`data/MNIST/TorchvisionDatasetWrapper/raw/train-images-idx3-ubyte` and `data/MNIST/TorchvisionDatasetWrapper/raw/train-images-idx3-ubyte.gz`

**Comment by Josep777** [comment]
Yes, that appears when you run the code with download=True when calling MNIST{...} function as it downloads the data straight from their website. The matter I'm referring to is when you have those files in the data/MNIST/TorchvisionDatasetWrapper/raw and you want to obtain the files in the ata/MNIST/TorchvisionDatasetWrapper/processed folder. How do you get those files? I thought when you ran the network with the raw files in the raw path the processed files in TorchvisionDatasetWrapper/processed would be generated by Bindsnet

**Comment by Hananel-Hazan** [comment]
BindsNET process the image via Torchvision parameters and conversion functions that convert pixel value to spike train. The conversion method in BindsNET do not save data to files. May be what you looking for is in the TorchVision part.

**Comment by Josep777** [comment]
And how to I look for those files' generation in TorchVision?

**Comment by Hananel-Hazan** [comment]
Googling your question I got the following [link](https://stackoverflow.com/questions/59915334/where-could-i-find-training-pt-test-pt).
From reading the answer you can understand that those files created by TorchVision.

Following the documentation of PyTorch TorchVision from older versions, its seems that those files were generated by PyTorch before version ~1.5.

From the PyTorch TorchVision documentation version [1.2.0](https://pytorch.org/docs/1.2.0/torchvision/datasets.html?highlight=mnist#mnist) those files are mentioned. But when reading the  PyTorch TorchVision latest documentation those files are no longer mentioned.

**Comment by Josep777** [comment]
Lots of thanks! I think we can close the issue here!
