### ISSUE TITLE
A (serious) bug preventing RL algorithms to work

### ISSUE THREAD

**Issue by ValerioB88** [BindsNET/bindsnet#577]
Hello all, and thank you for this beautiful library.

If have found a serious bug that would prevent any RL algorithm to work. The bug is in `select_softmax`, used in e.g. `breakout_stdp.py`
During the first iteration (time=0), `pipeline.spike_record[output]` has a `shape` os `[100, 4]` , `spike` is `tensor([0., 0., 0., 0.])`, so softmax is `tensor([0.25, 0.,25, 0.25, 0.25])` and it's all good.

However at any other timestep the dimension of `pipeline.spike_record[output]` has a shape of `tensor([100, 1, 4])`, `spike` is something like `tensor([[17., 17., 17., 17.])` which mean that `torch.softmax(spikes, dim=0)` is computing the softmax _on the wrong dimension_, and the result is always `probabilities = tensor([[1., 1., 1., 1.]])`, **meaning that the agent will always perform a random action.**

I am happy to fix this. In the meantime, I think it's good to share it as some people might get confused.
This issue is not impacting other examples such as `eth_minst.py`, that's why this net can learn supervised.

**Comment by SimonInParis** [comment]
Good catch. It looks like a batch extra dimension, added at some point?
What is the way to go? Add that extra dimension in any case?

Beware that `example/dotTracing/dot_tracing.py` also uses that function. No other examples uses it.

**Comment by ValerioB88** [comment]
The extra dimension is added in `Monitor.record()`, `data= getattr(self.obj, v)`.unsqueeze(0)`. 

The unsqueeze is adding the extra dimension, and commenting it out brings softmax to do the right thing. However I am not sure it's impacting anything else (the breakout example seems to work), and I haven't tried the `dot_tracing` example.

**Comment by Hananel-Hazan** [comment]
Thanks @ValerioB88 for letting us know, this is a good catch indeed. 
The extra dimension is the batch, that is why I agree with @SimonInParis change the line [79](https://github.com/BindsNET/bindsnet/blob/f4b550b78a5d5903f79264e74f8bec6537abd721/bindsnet/pipeline/action.py#L79) to be similar to line [110](https://github.com/BindsNET/bindsnet/blob/f4b550b78a5d5903f79264e74f8bec6537abd721/bindsnet/pipeline/action.py#L110)

@ValerioB88 If you can make a PR that will be great!

**Comment by ValerioB88** [comment]
Sure, will do!
