### ISSUE TITLE
Saving, loading, and performing prediction from supervised examples

### ISSUE THREAD

**Issue by TengHoo3** [BindsNET/bindsnet#584]
Hi there - currently I am testing on the supervised_mnist examples and was wondering whether there was a way to save the models and load them back for inference? I was able to save and load the model as per the usual way using PyTorch, but the 'forward' function does not seem to work if I use the DiehlAndCook2015 model.

![image](https://user-images.githubusercontent.com/67228311/190679562-4fe994e9-975c-46a8-b7b7-bc4d7152c524.png)

Could you advise on how to do inference on the images I am passing in after loading back the model? I'm specifically referring to **supervised_mnist.py** in bindsnet/examples/mnist/supervised_mnist.py

Thanks!

**Comment by Hananel-Hazan** [comment]
The functions load and save do operate on the network object. But in case of DiehlAndCook2015 model the `all_activity_pred` and `proportion_pred` need to be saved too, and load them during the inferences. Otherwise one need to redo the preferred neuron test again.
