### ISSUE TITLE
Is there any way to use BindsNet on RTX 3090?

### ISSUE THREAD

**Issue by leibniz21c** [BindsNET/bindsnet#585]
Following is my docker file 

```
FROM python:3.8.14

# copy dependencies
COPY requirements.txt .

# Dependencies
RUN apt-get update && \
    apt-get install -y git libgl1-mesa-glx && \
    pip3 install --upgrade pip && \
    pip3 install git+https://github.com/BindsNET/bindsnet.git && \
    pip3 install torch==1.7.1+cu110 torchvision==0.8.2+cu110 -f https://download.pytorch.org/whl/torch_stable.html && \
    pip3 install -r requirements.txt 
```

On the RTX 3090, 
we may use Python 3.8 or later and the version of PyTorch specified above. 
Can we use BindsNet at this time?

Thanks you for always.

**Comment by Hananel-Hazan** [comment]
BindsNET use PyTorch as a back end computation, using GPU is the preferred way to use BindsNET. 

However, using the newest version of BindsNET with PyTorch 1.7 may cause some issues, namely some bugs and syntax changes from PyTorch 1.7 to  the current version 1.12

Maybe you should use an older version of BindsNET, version that doesn't use poetry and the new pip installation, one that use `requirements.txt` like BindsNET version [0.2.9](https://github.com/BindsNET/bindsnet/releases/tag/0.2.9)
