### ISSUE TITLE
'bindsnet' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by rafaelblevin821** [BindsNET/bindsnet#594]
Hi folks,

I recently added some files to bindsnet, which caused a conflict that would not allow some of the functions to operate correctly. Therefore, after trying for a few hours to get it working, I decided to uninstall and reinstall it. 

However, after deleting, cleaning, and re-installing bindsnet, python does not recognize it as a program, even though it is showing up in the pip list of programs, 

I have tried adding the conda path to windows settings and environment variables, but still no resolution.

Any help is appreciated.
![2022-11-05_13-07-18](https://user-images.githubusercontent.com/1954873/200121917-9afcc35b-5bc1-447f-9114-8d3cabe0081e.png)
![2022-11-05_13-18-25](https://user-images.githubusercontent.com/1954873/200121918-783f9201-7821-429e-9422-1bb46b0378e8.png)

**Comment by Hananel-Hazan** [comment]
Did you try to create a new conda environment?

**Comment by rafaelblevin821** [comment]
Hi @Hananel-Hazan, it is now working. Set up a new conda environment and used python 3.9 instead of 3.10. Still shows as not recognized, but it's running networks, so all good. Thank you.
