### ISSUE TITLE
How would I run this type of setup?

### ISSUE THREAD

**Issue by ValerioB88** [BindsNET/bindsnet#597]
Hello, I am trying to replicate a particular experiment. The setup they use is quite simple but I think a bit tricky to implement in BindsNET: 
There are 1000 neurons connected all-to-all. I inject a strong current impulse to the first 50 of them, and let the network run for some time.
I created the all-to-all network in this way
```
network = Network(dt=1.0)
all_net = LIFNodes(n=network.num_neurons, refrac=0, traces=True, tresh=-60)
all_to_all_conn = Connection(source=all_net , target=net, w=None, wmin=-1, wmax=1, update_rule=network.update_rule, network=network)
    network.add_layer(net, name='N')
    network.add_connection(all_to_all_conn, source='N', target='N')

```
However, I am having trouble understanding what's the best way to make a set of neurons spike on commands. I think using an `InputNode` would not be appropriate, as that's basically a whole new layer that has its own weight and anyway applying a spike to the InputNode won't guarantee the correct neurons to spike. 
Another way could be to use the `inject_v` parameter and inject enough voltage to make them spike. Is this the best way to do this?

**Comment by SimonInParis** [comment]
Using the `injects_v` param is one good way. It will apply a constant voltage offset to the layer - eventually leading to spikes. You can also have the voltage offset vary in time, when adding the extra time dimension.
More simply, you can also pass the `clamp`/`unclamp` param to keep some neurons firing/non-firing.

**Comment by ValerioB88** [comment]
Oh, I didn't notice the `clamp` parameter, seems perfect for my use-case. Thanks Simon!
