### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._six'

### ISSUE THREAD

**Issue by Narcis67z** [BindsNET/bindsnet#619]
Hi all
I tried to install BindsNET on two different systems, I keep getting same error for torch._six. I tried to match versions but it didn't solve the problem.

**Comment by TheAwesomeAndy** [comment]
Just wanted to bump this ... same here.  Just recently started happening on Google Colab

**Comment by rafaelblevin821** [comment]
I had this isue in the past. I can't remember how I solved it. It could be the version of BindsNet you are using. 
Use `pip show bindsnet` to check your version.

**Comment by Hananel-Hazan** [comment]
Please provide more details to replicate your issue. I don't get this issue on my end.
What is your BindsNET version you try to install? (suggested @rafaelblevin821)
How do you installing BindsNET? 
What kind of environment do you have?

**Comment by TheAwesomeAndy** [comment]
!pip install Bindsnet
 -- works find

import Bindsnet

ImportError                               Traceback (most recent call last)
<ipython-input-2-7129a39e5cb0> in <module>
----> 1 import bindsnet

2 frames
/usr/local/lib/python3.9/dist-packages/bindsnet/datasets/collate.py in <module>
      9 
     10 import torch
---> 11 from torch._six import container_abcs, string_classes, int_classes
     12 
     13 from torch.utils.data._utils import collate as pytorch_collate

ImportError: cannot import name 'container_abcs' from 'torch._six' (/usr/local/lib/python3.9/dist-packages/torch/_six.py)
