### ISSUE TITLE
Are learning rules such as gradient descent available?

### ISSUE THREAD

**Issue by fun0515** [BindsNET/bindsnet#635]
I found that the examples given are all unsupervised training. I want to know if there are any supervised training methods, such as gradient descent. 
There is a supervised_mnist.py in ./examples/minist/, how does it work? I would greatly appreciate it if someone could provide an answer.

**Comment by Hananel-Hazan** [comment]
This question is relevant to the discussion section. 
For your question, please google Spike-timing-dependent plasticity (STDP), that the learning rule we are using in the BindsNET examples.
