### ISSUE TITLE
bug in examples/breakout

### ISSUE THREAD

**Issue by ioneliabuzatu** [BindsNET/bindsnet#677]
bug in https://github.com/BindsNET/bindsnet/blob/master/bindsnet/environment/environment.py#L92.

gym.make("env_name") instaed of gym.make(env_id="env_name"). at some point they changed the arg "env_id" to just "id"

original error when running random_baseline.py:
```
TypeError: make() missing 1 required positional argument: 'id'
```

**Comment by ioneliabuzatu** [comment]
another bug when running random_network_baseline.py

```
gymnasium.error.Error: Invalid render mode `None`. Supported modes: `human`, `rgb_array`.
```

to fix: https://github.com/BindsNET/bindsnet/blob/master/bindsnet/environment/environment.py#92L change it to
`self.env = gym.make(env_id=name, render_mode=render_mode)`









```
gymnasium.error.Error: Invalid render mode `None`. Supported modes: `human`, `rgb_array`.
```

to fix it

**Comment by Hananel-Hazan** [comment]
Can you make a PR with those changes?
