### ISSUE TITLE
Regarding Inhibitory Neurons and Excitatory Neurons Under Dale's Rule

### ISSUE THREAD

**Issue by Arueruma1999** [BindsNET/bindsnet#679]
Hi!

I'm recently trying to build up a RSNN network with Dale's rule using BindsNET. I'm wondering if there is a place I could define inhibitory neurons or excitatory neurons and keep sign of their weights unchanged during training.

Thank you in advance and looking foward to your reply!

Best,
Jinyu

**Comment by Hananel-Hazan** [comment]
Great question, please open a discussion post, this is not an issue with BindsNET code.

**Comment by Arueruma1999** [comment]
Sure, I opened a discussion post just right now. Thanks again!
&nbsp;


Jinyu&nbsp;Zang
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: "Hananel ***@***.***&gt;; 
Date: 2024年3月29日(星期五) 晚上10:14
To: ***@***.***&gt;; 
Cc: "Jinyu ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [BindsNET/bindsnet] Regarding Inhibitory Neurons and Excitatory Neurons Under Dale&#39;s Rule (Issue #679)














 
Great question, please open a discussion post, this is not an issue with BindsNET code.
